const $ = (q, root=document) => root.querySelector(q);
const $$ = (q, root=document) => [...root.querySelectorAll(q)];
const uid = () => (crypto?.randomUUID?.() || `id-${Date.now()}-${Math.random().toString(16).slice(2)}`);
const clone = v => JSON.parse(JSON.stringify(v));
const todayDisplay = () => new Intl.DateTimeFormat('es-CO',{year:'numeric',month:'long',day:'numeric'}).format(new Date());
const MAX_JSON_BYTES = 5*1024*1024, MAX_IMAGE_BYTES = 6*1024*1024;
const STORAGE_KEY='ei-docs-calidad-v2',HISTORY_KEY='ei-docs-calidad-history-v2';
const THEMES={institutional:{label:'Institucional EI',primary:'#001F73',secondary:'#00299B',accent:'#EAC800',muted:'#A4A8AB'},executive:{label:'Ejecutivo',primary:'#172554',secondary:'#1D4ED8',accent:'#38BDF8',muted:'#94A3B8'},technical:{label:'Técnico',primary:'#0F3D3E',secondary:'#176B66',accent:'#E9C46A',muted:'#9CA3AF'},safety:{label:'Seguridad',primary:'#7F1D1D',secondary:'#B91C1C',accent:'#F59E0B',muted:'#A3A3A3'},neutral:{label:'Minimalista',primary:'#111827',secondary:'#374151',accent:'#D1D5DB',muted:'#9CA3AF'}};
const BLOCK_LABELS={text:'Texto / subtítulo',table:'Tabla',chart:'Gráfica',kpi:'Indicador KPI',callout:'Nota destacada',citation:'Cita / referencia',bibliography:'Bibliografía',image:'Imagen / figura',list:'Lista',diagram:'Diagrama',pagebreak:'Salto de página'};
const HEADING_STYLES={heading2:{label:'Subtítulo · nivel 2',level:2},heading3:{label:'Subtítulo · nivel 3',level:3},heading4:{label:'Subtítulo · nivel 4',level:4},heading5:{label:'Subtítulo · nivel 5',level:5},heading6:{label:'Subtítulo · nivel 6',level:6}};
const DOC_TYPES=['oficio','circular','manual','guia','politica','protocolo','formato'],SGC_TYPES=['manual','guia','politica','protocolo','formato'];
function defaultBlock(type='text'){const base={id:uid(),type};if(type==='text')return{...base,style:'paragraph',numbered:true,text:'Desarrolle aquí el contenido técnico de la sección.'};if(type==='table')return{...base,title:'Tabla 1. Información',caption:'Fuente: elaboración propia.',striped:true,tableStyle:'institutional',align:'left',grid:'Criterio|Resultado\nEjemplo A|Cumple\nEjemplo B|En seguimiento'};if(type==='chart')return{...base,title:'Gráfica 1. Indicador',subtitle:'Evolución del indicador',chartType:'bar',labels:'Enero,Febrero,Marzo,Abril',values:'42,58,74,87',unit:'%',target:'80',caption:'Fuente: elaboración propia.'};if(type==='kpi')return{...base,label:'Cumplimiento',value:'87,9',unit:'%',trend:'+5,2 p.p.'};if(type==='callout')return{...base,kind:'info',title:'Nota técnica',text:'Incluya aquí una precisión, advertencia, recomendación o hallazgo.'};if(type==='citation')return{...base,referenceId:'',locator:'',narrative:false,quote:''};if(type==='bibliography')return{...base,title:'Referencias'};if(type==='image')return{...base,src:'',caption:'Figura 1. Descripción de la imagen.',alt:'Evidencia documental',width:100};if(type==='list')return{...base,ordered:false,items:'Elemento uno\nElemento dos\nElemento tres'};if(type==='diagram')return{...base,title:'Diagrama del proceso',items:'Entrada\nPreparación\nValidación\nSalida'};return{...base}}
function defaultSections(type='manual'){const map={manual:['OBJETIVO','ALCANCE','DEFINICIONES','CONTENIDO DEL MANUAL','DOCUMENTOS RELACIONADOS','CONTROL DE CAMBIOS'],guia:['OBJETIVO','ALCANCE','DESARROLLO DE LA GUÍA','RECOMENDACIONES','DOCUMENTOS RELACIONADOS','CONTROL DE CAMBIOS'],politica:['OBJETIVO','ALCANCE','LINEAMIENTOS','RESPONSABILIDADES','SEGUIMIENTO Y CUMPLIMIENTO','CONTROL DE CAMBIOS'],protocolo:['OBJETIVO','ALCANCE','CONDICIONES GENERALES','DESARROLLO DEL PROTOCOLO','RESPONSABLES Y REGISTROS','CONTROL DE CAMBIOS'],formato:['IDENTIFICACIÓN DEL FORMATO','CAMPOS DEL FORMATO','INSTRUCCIONES DE DILIGENCIAMIENTO','RESPONSABLE DEL REGISTRO','CONTROL DE CAMBIOS']};return(map[type]||map.manual).map((title,i)=>({id:uid(),number:String(i+1),title,blocks:[defaultBlock('text')]}))}
function defaultState(){return{schemaVersion:3,route:'home',zoom:.78,dirty:false,word:{type:'manual',title:'MANUAL DEL SISTEMA DE GESTIÓN',code:'X-XX-X',version:'Versión 1',cityDate:`Tuluá, ${todayDisplay()}`,pageSize:'letter',margin:'2.5',font:'Century Gothic',citationStyle:'apa7',themeKey:'institutional',theme:clone(THEMES.institutional),letter:{circularNo:'',para:'',de:'',asunto:'',body:'Escriba aquí el contenido del documento.',remitente:'NOMBRE DEL REMITENTE',cargo:'Cargo desempeñado'},sections:defaultSections('manual'),references:[]},instructivo:{title:'INSTRUCTIVO',code:'X-IN-X',version:'Versión 1',objective:'Definir el objetivo del instructivo.',scope:'Establecer su alcance.',theme:clone(THEMES.institutional),steps:[]}}}
let state=defaultState(),pendingImageTarget=null;
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function safeText(v,max=20000){return String(v??'').slice(0,max)}function isSgc(){return SGC_TYPES.includes(state.word.type)}function setDirty(on=true){state.dirty=on;const el=$('#saveState');if(el)el.textContent=on?'Cambios sin guardar':'Guardado'}function toast(message,kind='ok'){const box=$('#toastRegion'),el=document.createElement('div');el.className=`toast ${kind}`;el.textContent=message;box.appendChild(el);setTimeout(()=>el.remove(),2600)}
function fontStack(name){return{'Century Gothic':'"Century Gothic",Aptos,Arial,sans-serif',Aptos:'Aptos,Calibri,Arial,sans-serif',Arial:'Arial,sans-serif','Times New Roman':'"Times New Roman",serif'}[name]||'"Century Gothic",Aptos,Arial,sans-serif'}
function applyTheme(){const t=state.route==='instructivo'?state.instructivo.theme:state.word.theme,r=document.documentElement.style;r.setProperty('--doc-primary',t.primary);r.setProperty('--doc-secondary',t.secondary);r.setProperty('--doc-accent',t.accent);r.setProperty('--doc-muted',t.muted);r.setProperty('--font-doc',fontStack(state.word.font));const page=state.route==='word'&&state.word.pageSize==='a4'?'A4':'letter';let ps=document.getElementById('dynamicPrintPage');if(!ps){ps=document.createElement('style');ps.id='dynamicPrintPage';document.head.appendChild(ps)}ps.textContent=`@media print{@page{size:${page};margin:0}.paper{width:${page==='A4'?'8.27in':'8.5in'}!important}}`}
function normalizeTextStyle(style){return style==='subtitle'?'heading2':style&&HEADING_STYLES[style]?style:'paragraph'}function headingLevel(style){return HEADING_STYLES[normalizeTextStyle(style)]?.level||0}function headingNumber(section,blockIndex,level){const base=String(section?.number||'').trim()||'1',c={2:0,3:0,4:0,5:0,6:0};for(let i=0;i<=blockIndex;i++){const b=section?.blocks?.[i];if(b?.type!=='text')continue;const l=headingLevel(b.style);if(!l)continue;for(let p=2;p<l;p++)if(c[p]===0)c[p]=1;c[l]++;for(let d=l+1;d<=6;d++)c[d]=0}return[base,...Array.from({length:level-1},(_,k)=>c[k+2]||1)].join('.')}function headingDisplayText(block,section,blockIndex){const level=headingLevel(block?.style);if(!level)return String(block?.text||'');const prefix=block?.numbered===false?'':`${headingNumber(section,blockIndex,level)} `;return`${prefix}${String(block?.text||'')}`.trim()}function tocEntries(){const out=[];for(const s of state.word.sections||[]){out.push({level:1,number:String(s.number||''),title:String(s.title||'')});(s.blocks||[]).forEach((b,i)=>{const level=b.type==='text'?headingLevel(b.style):0;if(level)out.push({level,number:b.numbered===false?'':headingNumber(s,i,level),title:String(b.text||'')})})}return out}
function routeTo(route){state.route=route;applyTheme();$$('#homeView,#editorView').forEach(v=>v.classList.add('hidden'));if(route==='home')$('#homeView').classList.remove('hidden');else $('#editorView').classList.remove('hidden');$$('.nav-btn[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===route));const meta={home:['Centro documental','Panel principal'],word:['Editor documental','Word Studio'],instructivo:['Editor visual','Instructivos']}[route]||['Centro documental','Panel principal'];$('#routeEyebrow').textContent=meta[0];$('#routeTitle').textContent=meta[1];const exporting=route!=='home';['#exportPdfBtn','#exportDocxBtn','#zoomOutBtn','#zoomResetBtn','#zoomInBtn'].forEach(q=>$(q).classList.toggle('hidden',!exporting));renderSidebar();renderPreview();renderHomeMetrics()}
function renderHomeMetrics(){const sections=state.word.sections||[],blocks=sections.reduce((n,s)=>n+(s.blocks?.length||0),0);$('#homeSectionCount').textContent=sections.length;$('#homeBlockCount').textContent=blocks;$('#homeRefCount').textContent=(state.word.references||[]).length}
