function renderSidebar(){
  const box=$('#sidebarContent');
  if(state.route==='word') box.innerHTML=wordSidebarHtml();
  else if(state.route==='instructivo') box.innerHTML=instructivoSidebarHtml();
  else box.innerHTML=homeSidebarHtml();
  bindSidebar();
}
function homeSidebarHtml(){
  const hist=getHistory();
  return `<section class="side-card"><div class="side-card-head"><h2>Arquitectura limpia</h2><span class="status-dot">V3</span></div><p class="microcopy">Una sola fuente de estado, importación segura, autosave, Word real y vista previa sin contenido recortado.</p></section>
  <section class="side-card"><h2>Versiones locales</h2><div class="reference-list">${hist.length?hist.slice(0,6).map((h,i)=>`<div class="editor-card"><div class="editor-card-head"><span class="editor-card-title">${esc(h.label)}</span><button class="tiny-btn" data-history-open="${i}">Abrir</button></div><div class="ref-cite-preview">${esc(h.date)}</div></div>`).join(''):'<p class="microcopy">Aún no hay versiones guardadas.</p>'}</div></section>`;
}
function wordSidebarHtml(){
  const w=state.word,t=w.theme;
  return `<section class="side-card"><div class="side-card-head"><h2>Documento</h2><span class="status-dot">${esc(w.type.toUpperCase())}</span></div>
    <label class="field"><span>Tipo documental</span><select data-word="type">${DOC_TYPES.map(x=>`<option value="${x}" ${w.type===x?'selected':''}>${labelDocType(x)}</option>`).join('')}</select></label>
    <label class="field"><span>Título</span><input data-word="title" value="${esc(w.title)}"></label>
    <div class="field-row"><label class="field"><span>Código</span><input data-word="code" value="${esc(w.code)}"></label><label class="field"><span>Versión</span><input data-word="version" value="${esc(w.version)}"></label></div>
    <label class="field"><span>Ciudad y fecha</span><input data-word="cityDate" value="${esc(w.cityDate)}"></label>
  </section>
  ${!isSgc()?letterFieldsHtml():''}
  <section class="side-card"><div class="side-card-head"><h2>Diseño</h2><span class="status-dot">Tema</span></div>
    <label class="field"><span>Preset</span><select id="themePreset">${Object.entries(THEMES).map(([k,v])=>`<option value="${k}" ${w.themeKey===k?'selected':''}>${v.label}</option>`).join('')}<option value="custom" ${w.themeKey==='custom'?'selected':''}>Personalizado</option></select></label>
    <div class="palette-row">${[['primary','Primario'],['secondary','Secund.'],['accent','Acento'],['muted','Neutro']].map(([k,l])=>`<label class="field"><span>${l}</span><input type="color" data-theme="${k}" value="${esc(t[k])}"></label>`).join('')}</div>
    <div class="field-row"><label class="field"><span>Papel</span><select data-word="pageSize"><option value="letter" ${w.pageSize==='letter'?'selected':''}>Carta</option><option value="a4" ${w.pageSize==='a4'?'selected':''}>A4</option></select></label><label class="field"><span>Márgenes</span><select data-word="margin"><option value="2.5" ${w.margin==='2.5'?'selected':''}>2,5 cm</option><option value="3" ${w.margin==='3'?'selected':''}>3 cm</option></select></label></div>
    <div class="field-row"><label class="field"><span>Tipografía</span><select data-word="font">${['Century Gothic','Aptos','Arial','Times New Roman'].map(f=>`<option ${w.font===f?'selected':''}>${f}</option>`).join('')}</select></label><label class="field"><span>Citación</span><select data-word="citationStyle"><option value="apa7" ${w.citationStyle==='apa7'?'selected':''}>APA 7</option><option value="iso690" ${w.citationStyle==='iso690'?'selected':''}>ISO 690</option><option value="ieee" ${w.citationStyle==='ieee'?'selected':''}>Numérica / IEEE</option></select></label></div>
  </section>
  ${isSgc()?sectionsEditorHtml():''}
  ${isSgc()?referencesEditorHtml():''}`;
}
function letterFieldsHtml(){const l=state.word.letter;return `<section class="side-card"><h2>Contenido</h2>${state.word.type==='circular'?`<div class="field-row"><label class="field"><span>Circular No.</span><input data-letter="circularNo" value="${esc(l.circularNo)}"></label><label class="field"><span>Para</span><input data-letter="para" value="${esc(l.para)}"></label></div><div class="field-row"><label class="field"><span>De</span><input data-letter="de" value="${esc(l.de)}"></label><label class="field"><span>Asunto</span><input data-letter="asunto" value="${esc(l.asunto)}"></label></div>`:`<label class="field"><span>Asunto</span><input data-letter="asunto" value="${esc(l.asunto)}"></label>`}<label class="field"><span>Texto</span><textarea rows="7" data-letter="body">${esc(l.body)}</textarea></label><div class="field-row"><label class="field"><span>Remitente</span><input data-letter="remitente" value="${esc(l.remitente)}"></label><label class="field"><span>Cargo</span><input data-letter="cargo" value="${esc(l.cargo)}"></label></div></section>`}
function sectionsEditorHtml(){
  const w=state.word;
  return `<section class="side-card"><div class="side-card-head"><h2>Secciones y bloques</h2><button class="tiny-btn" id="addSectionBtn">+ Sección</button></div><div class="section-list">${w.sections.map((s,i)=>sectionEditorCard(s,i)).join('')}</div></section>`;
}
function sectionEditorCard(s,i){
  return `<div class="editor-card" data-section-card="${i}"><div class="editor-card-head"><span class="editor-card-title">${esc(s.number)} · ${esc(s.title)}</span><div><button class="tiny-btn" data-sec-move="up:${i}">↑</button><button class="tiny-btn" data-sec-move="down:${i}">↓</button><button class="tiny-btn danger" data-sec-delete="${i}">×</button></div></div>
    <div class="field-row"><label class="field"><span>Número</span><input data-sec-number="${i}" value="${esc(s.number)}"></label><label class="field"><span>Título</span><input data-sec-title="${i}" value="${esc(s.title)}"></label></div>
    <div>${(s.blocks||[]).map((b,j)=>blockEditorCard(b,i,j)).join('')}</div>
    <div class="add-block-row"><select data-add-block-type="${i}">${Object.entries(BLOCK_LABELS).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><button class="btn" data-add-block="${i}">+ Bloque</button></div>
  </div>`;
}
function blockEditorCard(b,i,j){
  const head=`<div class="block-toolbar"><span class="block-type">${esc(BLOCK_LABELS[b.type]||b.type)}</span><span class="block-actions"><button data-block-move="up:${i}:${j}">↑</button><button data-block-move="down:${i}:${j}">↓</button><button data-block-duplicate="${i}:${j}">⧉</button><button class="delete" data-block-delete="${i}:${j}">×</button></span></div>`;
  let body='';
  if(b.type==='text'){const st=normalizeTextStyle(b.style);body=`<label class="field"><span>Estilo / jerarquía</span><select data-block-field="${i}:${j}:style"><option value="paragraph" ${st==='paragraph'?'selected':''}>Párrafo</option>${Object.entries(HEADING_STYLES).map(([k,v])=>`<option value="${k}" ${st===k?'selected':''}>${v.label}</option>`).join('')}</select></label><label class="inline-check"><input type="checkbox" data-block-check="${i}:${j}:numbered" ${b.numbered!==false?'checked':''}> Numeración jerárquica automática (1.1 · 1.1.1 · …)</label><label class="field"><span>Contenido</span><textarea rows="4" data-block-field="${i}:${j}:text">${esc(b.text)}</textarea></label>`;}
  if(b.type==='table') body=`<label class="field"><span>Título</span><input data-block-field="${i}:${j}:title" value="${esc(b.title)}"></label><div class="field-row"><label class="field"><span>Estilo</span><select data-block-field="${i}:${j}:tableStyle"><option value="institutional" ${(b.tableStyle||'institutional')==='institutional'?'selected':''}>Institucional</option><option value="executive" ${b.tableStyle==='executive'?'selected':''}>Ejecutivo</option><option value="minimal" ${b.tableStyle==='minimal'?'selected':''}>Minimalista</option></select></label><label class="field"><span>Alineación</span><select data-block-field="${i}:${j}:align"><option value="left" ${(b.align||'left')==='left'?'selected':''}>Izquierda</option><option value="center" ${b.align==='center'?'selected':''}>Centrada</option><option value="right" ${b.align==='right'?'selected':''}>Derecha</option></select></label></div><label class="field"><span>Tabla · use | entre columnas y salto de línea entre filas</span><textarea rows="5" data-block-field="${i}:${j}:grid">${esc(b.grid)}</textarea></label><label class="field"><span>Fuente / nota</span><input data-block-field="${i}:${j}:caption" value="${esc(b.caption)}"></label><label class="inline-check"><input type="checkbox" data-block-check="${i}:${j}:striped" ${b.striped?'checked':''}> Filas alternas</label>`;
  if(b.type==='chart') body=`<label class="field"><span>Título</span><input data-block-field="${i}:${j}:title" value="${esc(b.title)}"></label><label class="field"><span>Subtítulo / contexto</span><input data-block-field="${i}:${j}:subtitle" value="${esc(b.subtitle||'')}"></label><div class="field-row"><label class="field"><span>Tipo</span><select data-block-field="${i}:${j}:chartType">${['bar','barh','line','donut'].map(x=>`<option value="${x}" ${b.chartType===x?'selected':''}>${{bar:'Columnas',barh:'Barras horizontales',line:'Línea',donut:'Dona'}[x]}</option>`).join('')}</select></label><label class="field"><span>Valores</span><input data-block-field="${i}:${j}:values" value="${esc(b.values)}"></label></div><div class="field-row"><label class="field"><span>Unidad</span><input data-block-field="${i}:${j}:unit" value="${esc(b.unit||'')}" placeholder="%, días, unidades…"></label><label class="field"><span>Meta / referencia</span><input data-block-field="${i}:${j}:target" value="${esc(b.target||'')}" placeholder="Opcional"></label></div><label class="field"><span>Etiquetas</span><input data-block-field="${i}:${j}:labels" value="${esc(b.labels)}"></label><label class="field"><span>Fuente / nota metodológica</span><input data-block-field="${i}:${j}:caption" value="${esc(b.caption)}"></label>`;
  if(b.type==='kpi') body=`<div class="field-row"><label class="field"><span>Indicador</span><input data-block-field="${i}:${j}:label" value="${esc(b.label)}"></label><label class="field"><span>Valor</span><input data-block-field="${i}:${j}:value" value="${esc(b.value)}"></label></div><div class="field-row"><label class="field"><span>Unidad</span><input data-block-field="${i}:${j}:unit" value="${esc(b.unit)}"></label><label class="field"><span>Tendencia</span><input data-block-field="${i}:${j}:trend" value="${esc(b.trend)}"></label></div>`;
  if(b.type==='callout') body=`<div class="field-row"><label class="field"><span>Tipo</span><select data-block-field="${i}:${j}:kind">${[['info','Información'],['note','Nota'],['tip','Recomendación'],['warning','Advertencia'],['success','Cumplimiento'],['danger','Riesgo']].map(([x,l])=>`<option value="${x}" ${b.kind===x?'selected':''}>${l}</option>`).join('')}</select></label><label class="field"><span>Título</span><input data-block-field="${i}:${j}:title" value="${esc(b.title)}"></label></div><label class="field"><span>Texto</span><textarea rows="3" data-block-field="${i}:${j}:text">${esc(b.text)}</textarea></label>`;
  if(b.type==='citation') body=`<label class="field"><span>Fuente</span><select data-block-field="${i}:${j}:referenceId"><option value="">Seleccione…</option>${state.word.references.map(r=>`<option value="${r.id}" ${b.referenceId===r.id?'selected':''}>${esc(shortRef(r))}</option>`).join('')}</select></label><label class="field"><span>Cita textual (opcional)</span><textarea rows="3" data-block-field="${i}:${j}:quote">${esc(b.quote||'')}</textarea></label><div class="field-row"><label class="field"><span>Página / localizador</span><input data-block-field="${i}:${j}:locator" value="${esc(b.locator)}"></label><label class="inline-check"><input type="checkbox" data-block-check="${i}:${j}:narrative" ${b.narrative?'checked':''}> Cita narrativa</label></div>`;
  if(b.type==='bibliography') body=`<label class="field"><span>Título</span><input data-block-field="${i}:${j}:title" value="${esc(b.title)}"></label><div class="ref-cite-preview">Se genera automáticamente con todas las fuentes registradas.</div>`;
  if(b.type==='image') body=`<button class="btn ghost" data-image-pick="${i}:${j}">${b.src?'Reemplazar imagen':'Cargar imagen'}</button>${b.src?`<button class="tiny-btn danger" data-image-clear="${i}:${j}">Quitar</button>`:''}<label class="field"><span>Pie de figura</span><input data-block-field="${i}:${j}:caption" value="${esc(b.caption)}"></label><label class="field"><span>Texto alternativo</span><input data-block-field="${i}:${j}:alt" value="${esc(b.alt)}"></label><label class="field"><span>Ancho %</span><input type="number" min="20" max="100" data-block-field="${i}:${j}:width" value="${esc(b.width)}"></label>`;
  if(b.type==='list') body=`<label class="inline-check"><input type="checkbox" data-block-check="${i}:${j}:ordered" ${b.ordered?'checked':''}> Lista numerada</label><label class="field"><span>Un elemento por línea</span><textarea rows="4" data-block-field="${i}:${j}:items">${esc(b.items)}</textarea></label>`;
  if(b.type==='diagram') body=`<label class="field"><span>Título</span><input data-block-field="${i}:${j}:title" value="${esc(b.title)}"></label><label class="field"><span>Etapas · una por línea</span><textarea rows="4" data-block-field="${i}:${j}:items">${esc(b.items)}</textarea></label>`;
  if(b.type==='pagebreak') body=`<div class="ref-cite-preview">Fuerza un salto de página en impresión y en Word.</div>`;
  return `<div class="block-card">${head}${body}</div>`;
}
function referencesEditorHtml(){return `<section class="side-card"><div class="side-card-head"><h2>Fuentes y citación</h2><button class="tiny-btn" id="addReferenceBtn">+ Fuente</button></div><div class="reference-list">${state.word.references.map((r,i)=>referenceCard(r,i)).join('')||'<p class="microcopy">Agregue fuentes para habilitar citas automáticas y bibliografía.</p>'}</div></section>`}
function referenceCard(r,i){return `<div class="editor-card"><div class="editor-card-head"><span class="editor-card-title">${esc(shortRef(r))}</span><button class="tiny-btn danger" data-ref-delete="${i}">×</button></div><label class="field"><span>Autor(es)</span><input data-ref-field="${i}:authors" value="${esc(r.authors)}" placeholder="Apellido, Nombre; Apellido, Nombre"></label><div class="field-row"><label class="field"><span>Año</span><input data-ref-field="${i}:year" value="${esc(r.year)}"></label><label class="field"><span>Tipo</span><select data-ref-field="${i}:type"><option value="web" ${r.type==='web'?'selected':''}>Web</option><option value="book" ${r.type==='book'?'selected':''}>Libro</option><option value="article" ${r.type==='article'?'selected':''}>Artículo</option><option value="standard" ${r.type==='standard'?'selected':''}>Norma</option><option value="law" ${r.type==='law'?'selected':''}>Ley / norma legal</option></select></label></div><label class="field"><span>Título</span><input data-ref-field="${i}:title" value="${esc(r.title)}"></label><label class="field"><span>Fuente / editorial / entidad</span><input data-ref-field="${i}:source" value="${esc(r.source)}"></label><label class="field"><span>URL o DOI</span><input data-ref-field="${i}:url" value="${esc(r.url)}"></label><div class="ref-cite-preview">${esc(formatReference(r))}</div></div>`}
function instructivoSidebarHtml(){const d=state.instructivo;return `<section class="side-card"><div class="side-card-head"><h2>Instructivo</h2><span class="status-dot">${d.steps.length} pasos</span></div><label class="field"><span>Título</span><input data-inst="title" value="${esc(d.title)}"></label><div class="field-row"><label class="field"><span>Código</span><input data-inst="code" value="${esc(d.code)}"></label><label class="field"><span>Versión</span><input data-inst="version" value="${esc(d.version)}"></label></div><label class="field"><span>Objetivo</span><textarea data-inst="objective">${esc(d.objective)}</textarea></label><label class="field"><span>Alcance</span><textarea data-inst="scope">${esc(d.scope)}</textarea></label></section><section class="side-card"><div class="side-card-head"><h2>Pasos</h2><button class="tiny-btn" id="addStepBtn">+ Paso</button></div><div class="step-list">${d.steps.map((s,i)=>stepEditorCard(s,i)).join('')||'<p class="microcopy">Agregue el primer paso.</p>'}</div></section>`}
function stepEditorCard(s,i){return `<div class="editor-card"><div class="editor-card-head"><span class="editor-card-title">${i+1}. ${esc(s.title||'Paso')}</span><div><button class="tiny-btn" data-step-move="up:${i}">↑</button><button class="tiny-btn" data-step-move="down:${i}">↓</button><button class="tiny-btn danger" data-step-delete="${i}">×</button></div></div><label class="field"><span>Título</span><input data-step-field="${i}:title" value="${esc(s.title)}"></label><label class="field"><span>Descripción</span><textarea rows="4" data-step-field="${i}:text">${esc(s.text)}</textarea></label><label class="field"><span>Nota</span><textarea rows="2" data-step-field="${i}:note">${esc(s.note)}</textarea></label><div class="actions"><button class="btn ghost" data-step-image="${i}">${s.image?'Reemplazar imagen':'Cargar imagen'}</button>${s.image?`<button class="tiny-btn danger" data-step-image-clear="${i}">Quitar</button>`:''}</div></div>`}
function bindSidebar(){
  $$('[data-route]').forEach(b=>b.onclick=()=>routeTo(b.dataset.route));$$('[data-history-open]').forEach(b=>b.onclick=()=>openHistory(+b.dataset.historyOpen));
  $$('[data-word]').forEach(el=>el.oninput=()=>{const k=el.dataset.word,oldType=state.word.type;state.word[k]=el.value;let refresh=false;if(k==='type'&&oldType!==el.value){refresh=true;if(SGC_TYPES.includes(el.value)&&!confirmKeepSections())state.word.sections=defaultSections(el.value)}applyTheme();changed(refresh)});
  $$('[data-letter]').forEach(el=>el.oninput=()=>{state.word.letter[el.dataset.letter]=safeText(el.value);changed(false)});const preset=$('#themePreset');if(preset)preset.onchange=()=>{state.word.themeKey=preset.value;if(THEMES[preset.value])state.word.theme=clone(THEMES[preset.value]);applyTheme();changed(true)};$$('[data-theme]').forEach(el=>el.oninput=()=>{state.word.themeKey='custom';state.word.theme[el.dataset.theme]=el.value;applyTheme();changed(false)});
  const addSec=$('#addSectionBtn');if(addSec)addSec.onclick=()=>{state.word.sections.push({id:uid(),number:String(state.word.sections.length+1),title:'NUEVA SECCIÓN',blocks:[defaultBlock('text')]});changed(true)};$$('[data-sec-number]').forEach(el=>el.oninput=()=>{state.word.sections[+el.dataset.secNumber].number=safeText(el.value,20);changed(false)});$$('[data-sec-title]').forEach(el=>el.oninput=()=>{state.word.sections[+el.dataset.secTitle].title=safeText(el.value,200);changed(false)});$$('[data-sec-delete]').forEach(el=>el.onclick=()=>{state.word.sections.splice(+el.dataset.secDelete,1);renumberSections();changed(true)});$$('[data-sec-move]').forEach(el=>el.onclick=()=>{const[dir,i]=el.dataset.secMove.split(':');moveItem(state.word.sections,+i,dir);changed(true)});
  $$('[data-add-block]').forEach(el=>el.onclick=()=>{const i=+el.dataset.addBlock,sel=$(`[data-add-block-type="${i}"]`);state.word.sections[i].blocks.push(defaultBlock(sel.value));changed(true)});$$('[data-block-field]').forEach(el=>el.oninput=()=>{const[i,j,k]=el.dataset.blockField.split(':');let v=el.value;if(k==='width')v=Math.max(20,Math.min(100,+v||100));state.word.sections[+i].blocks[+j][k]=v;changed(false)});$$('[data-block-check]').forEach(el=>el.onchange=()=>{const[i,j,k]=el.dataset.blockCheck.split(':');state.word.sections[+i].blocks[+j][k]=el.checked;changed(false)});$$('[data-block-delete]').forEach(el=>el.onclick=()=>{const[i,j]=el.dataset.blockDelete.split(':').map(Number);state.word.sections[i].blocks.splice(j,1);changed(true)});$$('[data-block-duplicate]').forEach(el=>el.onclick=()=>{const[i,j]=el.dataset.blockDuplicate.split(':').map(Number),cp=clone(state.word.sections[i].blocks[j]);cp.id=uid();state.word.sections[i].blocks.splice(j+1,0,cp);changed(true)});$$('[data-block-move]').forEach(el=>el.onclick=()=>{const[dir,i,j]=el.dataset.blockMove.split(':');moveItem(state.word.sections[+i].blocks,+j,dir);changed(true)});$$('[data-image-pick]').forEach(el=>el.onclick=()=>{pendingImageTarget={kind:'block',path:el.dataset.imagePick};$('#hiddenImageInput').click()});$$('[data-image-clear]').forEach(el=>el.onclick=()=>{const[i,j]=el.dataset.imageClear.split(':').map(Number);state.word.sections[i].blocks[j].src='';changed(true)});
  const addRef=$('#addReferenceBtn');if(addRef)addRef.onclick=()=>{state.word.references.push({id:uid(),type:'web',authors:'',year:new Date().getFullYear(),title:'Nueva fuente',source:'',url:''});changed(true)};$$('[data-ref-field]').forEach(el=>el.oninput=()=>{const[i,k]=el.dataset.refField.split(':');state.word.references[+i][k]=safeText(el.value,1000);changed(false)});$$('[data-ref-delete]').forEach(el=>el.onclick=()=>{const r=state.word.references.splice(+el.dataset.refDelete,1)[0];state.word.sections.forEach(s=>s.blocks.forEach(b=>{if(b.type==='citation'&&b.referenceId===r.id)b.referenceId=''}));changed(true)});
  $$('[data-inst]').forEach(el=>el.oninput=()=>{state.instructivo[el.dataset.inst]=safeText(el.value);changed(false)});const addStep=$('#addStepBtn');if(addStep)addStep.onclick=()=>{state.instructivo.steps.push({id:uid(),title:`Paso ${state.instructivo.steps.length+1}`,text:'Describa la actividad.',note:'',image:''});changed(true)};$$('[data-step-field]').forEach(el=>el.oninput=()=>{const[i,k]=el.dataset.stepField.split(':');state.instructivo.steps[+i][k]=safeText(el.value);changed(false)});$$('[data-step-delete]').forEach(el=>el.onclick=()=>{state.instructivo.steps.splice(+el.dataset.stepDelete,1);changed(true)});$$('[data-step-move]').forEach(el=>el.onclick=()=>{const[dir,i]=el.dataset.stepMove.split(':');moveItem(state.instructivo.steps,+i,dir);changed(true)});$$('[data-step-image]').forEach(el=>el.onclick=()=>{pendingImageTarget={kind:'step',index:+el.dataset.stepImage};$('#hiddenImageInput').click()});$$('[data-step-image-clear]').forEach(el=>el.onclick=()=>{state.instructivo.steps[+el.dataset.stepImageClear].image='';changed(true)});
}
function confirmKeepSections(){return state.word.sections?.length?confirm('¿Conservar las secciones actuales al cambiar el tipo documental?\nAceptar = conservar · Cancelar = cargar estructura recomendada'):false}
function changed(fullSidebar=false){setDirty(true);applyTheme();renderPreview();renderHomeMetrics();if(fullSidebar)renderSidebar();autoSaveDebounced()}let autoSaveTimer=null;function autoSaveDebounced(){clearTimeout(autoSaveTimer);autoSaveTimer=setTimeout(()=>saveLocal(false),650)}function moveItem(arr,index,dir){const to=dir==='up'?index-1:index+1;if(to<0||to>=arr.length)return;[arr[index],arr[to]]=[arr[to],arr[index]]}function renumberSections(){state.word.sections.forEach((s,i)=>s.number=String(i+1))}function labelDocType(t){return{oficio:'Oficio',circular:'Circular',manual:'Manual',guia:'Guía',politica:'Política',protocolo:'Protocolo',formato:'Formato'}[t]||t}
