async function exportDocx(){try{toast('Preparando archivo Word…');const mod=await import('https://cdn.jsdelivr.net/npm/docx@9.7.1/+esm');const blob=state.route==='instructivo'?await buildInstructivoDocx(mod):await buildWordDocx(mod);downloadBlob(blob,`${fileBase()}.docx`);toast('Word generado correctamente.')}catch(e){console.error(e);toast('No fue posible generar el DOCX. Verifique la conexión e intente de nuevo.','error')}}
async function buildWordDocx(D){return isSgc()?buildSgcDocx(D):buildLetterDocx(D)}
function docxThemeColor(hex){return String(hex||'#001F73').replace('#','').toUpperCase()}
function docxText(D,text,opt={}){return new D.TextRun({text:String(text??''),font:state.word.font||'Century Gothic',size:opt.size||20,bold:!!opt.bold,color:opt.color,italics:!!opt.italics})}
function docxHeader(D,title,code,version){return new D.Header({children:[new D.Table({width:{size:100,type:D.WidthType.PERCENTAGE},rows:[new D.TableRow({children:[new D.TableCell({width:{size:22,type:D.WidthType.PERCENTAGE},children:[new D.Paragraph({alignment:D.AlignmentType.CENTER,children:[docxText(D,'ELECTROINGENIERÍA',{bold:true,size:15,color:docxThemeColor(state.word.theme.primary)})]})]}),new D.TableCell({width:{size:58,type:D.WidthType.PERCENTAGE},shading:{fill:docxThemeColor(state.word.theme.primary)},children:[new D.Paragraph({alignment:D.AlignmentType.CENTER,children:[docxText(D,title||'DOCUMENTO',{bold:true,size:17,color:docxThemeColor(state.word.theme.accent)})]})]}),new D.TableCell({width:{size:20,type:D.WidthType.PERCENTAGE},shading:{fill:docxThemeColor(state.word.theme.primary)},children:[new D.Paragraph({alignment:D.AlignmentType.CENTER,children:[docxText(D,code||'',{bold:true,size:14,color:'FFFFFF'})]}),new D.Paragraph({alignment:D.AlignmentType.CENTER,children:[docxText(D,version||'',{bold:true,size:14,color:'FFFFFF'})]})]})]})]})]})}
function docxFooter(D){return new D.Footer({children:[new D.Paragraph({alignment:D.AlignmentType.RIGHT,children:[docxText(D,'Página ',{size:15,color:'667085'}),new D.TextRun({children:[D.PageNumber.CURRENT],size:15}),docxText(D,' de ',{size:15,color:'667085'}),new D.TextRun({children:[D.PageNumber.TOTAL_PAGES],size:15})]})]})}
function docxSectionProps(){const letter={width:12240,height:15840},a4={width:11906,height:16838},size=state.word.pageSize==='a4'?a4:letter,cm=state.word.margin==='3'?1701:1417;return {page:{size,margin:{top:cm,right:cm,bottom:cm,left:cm}}}}
async function buildSgcDocx(D){
  const children=[new D.Paragraph({text:'TABLA DE CONTENIDO',heading:D.HeadingLevel.HEADING_1,alignment:D.AlignmentType.CENTER}),new D.TableOfContents('Tabla de contenido',{hyperlink:true,headingStyleRange:'1-6'}),new D.Paragraph({children:[new D.PageBreak()]})];
  for(const [si,s] of state.word.sections.entries()){
    children.push(new D.Paragraph({heading:D.HeadingLevel.HEADING_1,spacing:{before:220,after:100},children:[docxText(D,`${s.number||si+1}  ${s.title}`,{bold:true,size:22,color:docxThemeColor(state.word.theme.primary)})]}));
    for(const [bi,b] of (s.blocks||[]).entries())children.push(...await docxBlock(D,b,s,bi));
  }
  const doc=new D.Document({creator:'Centro Documental EI',title:state.word.title,description:'Documento generado por Centro Documental EI',styles:{default:{document:{run:{font:state.word.font||'Century Gothic',size:20},paragraph:{spacing:{after:120,line:276}}}}},sections:[{properties:docxSectionProps(),headers:{default:docxHeader(D,state.word.title,state.word.code,state.word.version)},footers:{default:docxFooter(D)},children}]});
  return D.Packer.toBlob(doc)
}
async function buildLetterDocx(D){const l=state.word.letter,children=[new D.Paragraph({alignment:D.AlignmentType.RIGHT,children:[docxText(D,state.word.cityDate)]})];if(state.word.type==='circular')children.push(new D.Paragraph({alignment:D.AlignmentType.CENTER,children:[docxText(D,`CIRCULAR No. ${l.circularNo}`,{bold:true})]}),new D.Paragraph({children:[docxText(D,'PARA: ',{bold:true}),docxText(D,l.para)]}),new D.Paragraph({children:[docxText(D,'DE: ',{bold:true}),docxText(D,l.de)]}));children.push(new D.Paragraph({children:[docxText(D,'ASUNTO: ',{bold:true}),docxText(D,l.asunto)]}));String(l.body||'').split(/\n/).forEach(p=>children.push(new D.Paragraph({alignment:D.AlignmentType.JUSTIFIED,children:[docxText(D,p)]})));children.push(new D.Paragraph({spacing:{before:700},children:[docxText(D,'_____________________________')]}),new D.Paragraph({children:[docxText(D,l.remitente,{bold:true})]}),new D.Paragraph({children:[docxText(D,l.cargo)]}));const doc=new D.Document({sections:[{properties:docxSectionProps(),footers:{default:docxFooter(D)},children}]});return D.Packer.toBlob(doc)}
async function docxBlock(D,b,section=null,blockIndex=0){
  const out=[];
  if(b.type==='text'){const level=headingLevel(b.style);if(level){const map={2:D.HeadingLevel.HEADING_2,3:D.HeadingLevel.HEADING_3,4:D.HeadingLevel.HEADING_4,5:D.HeadingLevel.HEADING_5,6:D.HeadingLevel.HEADING_6},sizes={2:20,3:19,4:18,5:17,6:16};out.push(new D.Paragraph({heading:map[level],spacing:{before:160,after:70},children:[docxText(D,headingDisplayText(b,section,blockIndex),{bold:true,size:sizes[level],color:docxThemeColor(state.word.theme.primary)})]}))}else String(b.text||'').split(/\n/).forEach(p=>out.push(new D.Paragraph({alignment:D.AlignmentType.JUSTIFIED,children:[docxText(D,p)]})));}
  else if(b.type==='table'){if(b.title)out.push(new D.Paragraph({children:[docxText(D,b.title,{bold:true,color:docxThemeColor(state.word.theme.primary)})]}));const rows=parseGrid(b.grid),align=b.align==='center'?D.AlignmentType.CENTER:b.align==='right'?D.AlignmentType.RIGHT:D.AlignmentType.LEFT,headerFill=b.tableStyle==='minimal'?'F3F4F6':b.tableStyle==='executive'?docxThemeColor(state.word.theme.secondary):docxThemeColor(state.word.theme.primary),headerColor=b.tableStyle==='minimal'?docxThemeColor(state.word.theme.primary):'FFFFFF';if(rows.length)out.push(new D.Table({width:{size:100,type:D.WidthType.PERCENTAGE},rows:rows.map((r,ri)=>new D.TableRow({children:r.map(c=>new D.TableCell({shading:ri===0?{fill:headerFill}:undefined,children:[new D.Paragraph({alignment:align,children:[docxText(D,c,{bold:ri===0,color:ri===0?headerColor:undefined,size:17})]})]}))}))}));if(b.caption)out.push(new D.Paragraph({alignment:D.AlignmentType.CENTER,children:[docxText(D,b.caption,{italics:true,size:15,color:'667085'})]}));}
  else if(b.type==='chart'){out.push(new D.Paragraph({children:[docxText(D,b.title,{bold:true,color:docxThemeColor(state.word.theme.primary)})]}));if(b.subtitle)out.push(new D.Paragraph({children:[docxText(D,b.subtitle,{italics:true,size:16,color:'667085'})]}));const svg=chartSvgMarkup(b,640,270);out.push(new D.Paragraph({alignment:D.AlignmentType.CENTER,children:[new D.ImageRun({data:new TextEncoder().encode(svg),transformation:{width:580,height:245},type:'svg'})]}));if(b.caption)out.push(new D.Paragraph({alignment:D.AlignmentType.CENTER,children:[docxText(D,b.caption,{italics:true,size:15,color:'667085'})]}));}
  else if(b.type==='kpi')out.push(new D.Table({width:{size:45,type:D.WidthType.PERCENTAGE},rows:[new D.TableRow({children:[new D.TableCell({shading:{fill:'F5F7FB'},children:[new D.Paragraph({children:[docxText(D,b.label,{size:16,color:'667085'})]}),new D.Paragraph({children:[docxText(D,`${b.value}${b.unit}`,{bold:true,size:30,color:docxThemeColor(state.word.theme.primary)})]}),new D.Paragraph({children:[docxText(D,b.trend||'',{bold:true,size:14,color:'067647'})]})]})]})]}));
  else if(b.type==='callout')out.push(new D.Table({width:{size:100,type:D.WidthType.PERCENTAGE},rows:[new D.TableRow({children:[new D.TableCell({shading:{fill:b.kind==='warning'?'FFF8E1':(b.kind==='success'||b.kind==='tip')?'ECFDF3':b.kind==='danger'?'FEF3F2':b.kind==='note'?'F8F4FF':'EEF3FF'},children:[new D.Paragraph({children:[docxText(D,b.title,{bold:true,color:docxThemeColor(state.word.theme.primary)})]}),new D.Paragraph({children:[docxText(D,b.text)]})]})]})]}));
  else if(b.type==='citation'){if(b.quote)out.push(new D.Paragraph({indent:{left:560,right:280},spacing:{before:80,after:70},children:[docxText(D,`“${b.quote}”`,{italics:true,color:'344054'})]}));out.push(new D.Paragraph({children:[docxText(D,formatCitationById(b.referenceId,b.locator,b.narrative),{italics:true})]}));}
  else if(b.type==='bibliography'){out.push(new D.Paragraph({heading:D.HeadingLevel.HEADING_2,children:[docxText(D,b.title||'Referencias',{bold:true,color:docxThemeColor(state.word.theme.primary)})]}));state.word.references.forEach(r=>out.push(new D.Paragraph({hanging:360,children:[docxText(D,formatReference(r),{size:18})]})))}
  else if(b.type==='image'&&safeImageSrc(b.src)){const {bytes,type}=dataUrlBytes(b.src);out.push(new D.Paragraph({alignment:D.AlignmentType.CENTER,children:[new D.ImageRun({data:bytes,transformation:{width:Math.round(580*(Math.max(20,Math.min(100,+b.width||100))/100)),height:330},type})]}));if(b.caption)out.push(new D.Paragraph({alignment:D.AlignmentType.CENTER,children:[docxText(D,b.caption,{italics:true,size:15,color:'667085'})]}));}
  else if(b.type==='list'){lines(b.items).forEach((x,i)=>out.push(new D.Paragraph({children:[docxText(D,`${b.ordered?`${i+1}.`:'•'} ${x}`)]})))}
  else if(b.type==='diagram'){if(b.title)out.push(new D.Paragraph({children:[docxText(D,b.title,{bold:true,color:docxThemeColor(state.word.theme.primary)})]}));const svg=diagramSvgMarkup(b);out.push(new D.Paragraph({alignment:D.AlignmentType.CENTER,children:[new D.ImageRun({data:new TextEncoder().encode(svg),transformation:{width:580,height:163},type:'svg'})]}));}
  else if(b.type==='pagebreak')out.push(new D.Paragraph({children:[new D.PageBreak()]}));
  return out;
}
function dataUrlBytes(src){const m=String(src).match(/^data:image\/(png|jpeg|jpg|webp|gif);base64,(.+)$/i);if(!m)throw new Error('Imagen no compatible');const type=m[1].toLowerCase()==='jpg'?'jpeg':m[1].toLowerCase(),bin=atob(m[2]),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return {bytes,type}}
async function buildInstructivoDocx(D){const d=state.instructivo,children=[new D.Paragraph({heading:D.HeadingLevel.HEADING_1,alignment:D.AlignmentType.CENTER,children:[docxText(D,d.title,{bold:true,size:26,color:docxThemeColor(d.theme.primary)})]}),new D.Paragraph({children:[docxText(D,'OBJETIVO: ',{bold:true}),docxText(D,d.objective)]}),new D.Paragraph({children:[docxText(D,'ALCANCE: ',{bold:true}),docxText(D,d.scope)]})];for(const [i,s] of d.steps.entries()){children.push(new D.Paragraph({heading:D.HeadingLevel.HEADING_2,children:[docxText(D,`${i+1}. ${s.title}`,{bold:true,color:docxThemeColor(d.theme.primary)})]}),new D.Paragraph({children:[docxText(D,s.text)]}));if(s.image&&safeImageSrc(s.image)){const {bytes,type}=dataUrlBytes(s.image);children.push(new D.Paragraph({alignment:D.AlignmentType.CENTER,children:[new D.ImageRun({data:bytes,transformation:{width:560,height:320},type})]}))}if(s.note)children.push(new D.Paragraph({children:[docxText(D,`Nota: ${s.note}`,{italics:true})]}));}const doc=new D.Document({sections:[{properties:docxSectionProps(),headers:{default:docxHeader(D,d.title,d.code,d.version)},footers:{default:docxFooter(D)},children}]});return D.Packer.toBlob(doc)}

function newProject(){if(state.dirty&&!confirm('Hay cambios sin guardar. ¿Crear un proyecto nuevo?'))return;state=defaultState();applyTheme();setDirty(false);routeTo('home');toast('Proyecto nuevo creado.')}
function setZoom(v){state.zoom=Math.max(.42,Math.min(1.18,v));renderPreview()}
function bindGlobal(){
  $$('#brandHome,[data-route]').forEach(b=>b.onclick=()=>routeTo(b.dataset.route||'home'));
  $$('[data-open-card]').forEach(b=>b.onclick=()=>routeTo(b.dataset.openCard));
  $('#zoomOutBtn').onclick=()=>setZoom(state.zoom-.05);$('#zoomInBtn').onclick=()=>setZoom(state.zoom+.05);$('#zoomResetBtn').onclick=()=>setZoom(.78);
  $('#exportPdfBtn').onclick=()=>window.print();$('#exportDocxBtn').onclick=exportDocx;
  $('#saveLocalBtn').onclick=()=>saveLocal(true);$('#downloadJsonBtn').onclick=downloadJson;$('#openJsonInput').onchange=e=>{openJson(e.target.files?.[0]);e.target.value=''};$('#newProjectBtn').onclick=newProject;
  $('#hiddenImageInput').onchange=e=>{imageToTarget(e.target.files?.[0]);e.target.value=''};
  window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue=''}});
}
function selfTest(){const errors=[];if(!Array.isArray(state.word.sections))errors.push('Secciones inválidas');if(!Array.isArray(state.word.references))errors.push('Referencias inválidas');if(!Array.isArray(state.instructivo.steps))errors.push('Pasos inválidos');for(const s of state.word.sections){if(!Array.isArray(s.blocks)){errors.push(`Bloques inválidos en ${s.title}`);continue}for(const b of s.blocks){if(!BLOCK_LABELS[b.type])errors.push(`Tipo de bloque desconocido: ${b.type}`);if(b.type==='text'&&normalizeTextStyle(b.style)!=='paragraph'&&!headingLevel(b.style))errors.push('Jerarquía de título inválida')}}if(!['apa7','iso690','ieee'].includes(state.word.citationStyle))errors.push('Estilo de citación inválido');console.info(`[EI QA] ${errors.length?'FAIL':'PASS'}`,errors);return errors}
function init(){loadLocal();applyTheme();bindGlobal();routeTo(state.route||'home');setDirty(false);selfTest()}
init();
