function renderPreview(){
  if(state.route==='home')return;
  applyTheme();
  const stage=$('#previewStage');stage.style.transform=`scale(${state.zoom})`;
  $('#zoomResetBtn').textContent=`${Math.round(state.zoom*100)}%`;
  stage.innerHTML=state.route==='word'?wordPreviewHtml():instructivoPreviewHtml();
}
function paperClass(){return `paper ${state.word.pageSize==='a4'?'a4':''}`}
function paperAttrs(){return `class="${paperClass()}" data-margin="${esc(state.word.margin)}"`}
function headerHtml(title=state.word.title,code=state.word.code,version=state.word.version){return `<div class="paper-head"><div class="paper-head-logo"><img src="assets/header-ei-calidad.png" alt="Electroingeniería"></div><div class="paper-head-title">${esc(title||'DOCUMENTO')}</div><div class="paper-head-meta"><span>${esc(code||'X-XX-X')}</span><span>${esc(version||'VERSIÓN')}</span></div></div>`}
function footerHtml(){return `<div class="paper-footer"><img src="assets/footer-ei-calidad.png" alt="Electroingeniería"><span>Vista continua · paginación automática al exportar</span></div>`}
function wordPreviewHtml(){return isSgc()?sgcPreviewHtml():letterPreviewHtml()}
function letterPreviewHtml(){const w=state.word,l=w.letter,isCircular=w.type==='circular';return `<article ${paperAttrs()}><div class="paper-inner"><div class="letterhead"></div><div class="letter-body"><p class="date">${esc(w.cityDate)}</p>${isCircular?`<p style="text-align:center"><b>CIRCULAR No. ${esc(l.circularNo)}</b></p><p><b>PARA:</b> ${esc(l.para)}</p><p><b>DE:</b> ${esc(l.de)}</p>`:''}<p class="subject"><b>ASUNTO:</b> ${esc(l.asunto)}</p>${esc(l.body).replace(/\n/g,'<br>')}<div class="letter-signature"><div class="signature-line"></div><b>${esc(l.remitente)}</b><br><span>${esc(l.cargo)}</span></div></div>${footerHtml()}</div></article>`}
function sgcPreviewHtml(){
  const w=state.word;
  const toc=`<article ${paperAttrs()}><div class="paper-inner">${headerHtml()}<h2 class="toc-title">TABLA DE CONTENIDO</h2>${tocEntries().map(e=>`<div class="toc-row toc-level-${e.level}"><b>${esc(e.number)}</b><span>${esc(e.title)}</span><i class="toc-dots"></i><small>automático</small></div>`).join('')}${footerHtml()}</div></article>`;
  const body=`<article ${paperAttrs()}><div class="paper-inner">${headerHtml()}${w.sections.map((s,i)=>sectionPreviewHtml(s,i)).join('')}${footerHtml()}</div></article>`;
  return toc+body;
}
function sectionPreviewHtml(s,i){return `<section class="doc-section"><div class="section-heading"><span>${esc(s.number||i+1)}</span><small>${esc(s.title)}</small></div>${(s.blocks||[]).map((b,j)=>blockPreviewHtml(b,s,j)).join('')}</section>`}
function blockPreviewHtml(b,section=null,blockIndex=0){
  if(b.type==='text'){const level=headingLevel(b.style);if(level)return `<div class="doc-block"><div class="doc-heading doc-heading-${level}">${esc(headingDisplayText(b,section,blockIndex))}</div></div>`;return `<div class="doc-block doc-text">${esc(b.text).replace(/\n/g,'<br>')}</div>`;}
  if(b.type==='table') return tablePreviewHtml(b);
  if(b.type==='chart') return `<div class="doc-block chart-shell"><div class="chart-title">${esc(b.title)}</div>${b.subtitle?`<div class="chart-subtitle">${esc(b.subtitle)}</div>`:''}${chartSvgMarkup(b)}<div class="chart-caption">${esc(b.caption)}</div></div>`;
  if(b.type==='kpi') return `<div class="doc-block kpi-grid"><div class="kpi-card"><span>${esc(b.label)}</span><b>${esc(b.value)}${esc(b.unit)}</b>${b.trend?`<em>${esc(b.trend)}</em>`:''}</div></div>`;
  if(b.type==='callout') return `<div class="doc-block callout ${esc(b.kind)}"><b>${esc(b.title)}</b>${esc(b.text)}</div>`;
  if(b.type==='citation') return `<div class="doc-block citation-block">${b.quote?`<blockquote class="quote-block">“${esc(b.quote)}”</blockquote>`:''}<span class="citation-pill">${esc(formatCitationById(b.referenceId,b.locator,b.narrative))}</span></div>`;
  if(b.type==='bibliography') return `<div class="doc-block bibliography"><div class="doc-subtitle">${esc(b.title||'Referencias')}</div>${state.word.references.length?state.word.references.map(r=>`<div class="bibliography-entry">${esc(formatReference(r))}</div>`).join(''):'<div class="bibliography-entry">No hay fuentes registradas.</div>'}</div>`;
  if(b.type==='image') return `<figure class="doc-block doc-image">${b.src?`<img src="${safeImageSrc(b.src)}" alt="${esc(b.alt||'Imagen')}" style="width:${Math.max(20,Math.min(100,+b.width||100))}%">`:'<div class="callout">Imagen pendiente de cargar.</div>'}<figcaption class="figure-caption">${esc(b.caption)}</figcaption></figure>`;
  if(b.type==='list'){const items=lines(b.items);const tag=b.ordered?'ol':'ul';return `<${tag} class="doc-block doc-list">${items.map(x=>`<li>${esc(x)}</li>`).join('')}</${tag}>`}
  if(b.type==='diagram') return `<div class="doc-block"><div class="diagram-title">${esc(b.title)}</div><div class="diagram-flow">${lines(b.items).map((x,i,a)=>`<div class="diagram-node">${esc(x)}</div>${i<a.length-1?'<div class="diagram-arrow">→</div>':''}`).join('')}</div></div>`;
  if(b.type==='pagebreak') return `<div class="pagebreak-indicator">SALTO DE PÁGINA</div>`;
  return '';
}
function tablePreviewHtml(b){const rows=parseGrid(b.grid);if(!rows.length)return '';const style=['institutional','executive','minimal'].includes(b.tableStyle)?b.tableStyle:'institutional',align=['left','center','right'].includes(b.align)?b.align:'left';return `<div class="doc-block"><div class="doc-table-title">${esc(b.title)}</div><div class="doc-table-wrap table-style-${style}"><table class="doc-table ${b.striped?'striped':''} align-${align}"><thead><tr>${rows[0].map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${rows.slice(1).map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="chart-caption">${esc(b.caption)}</div></div>`}
function parseGrid(v){return String(v||'').split(/\r?\n/).map(r=>r.split('|').map(c=>c.trim())).filter(r=>r.some(Boolean)).slice(0,50)}
function lines(v){return String(v||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).slice(0,40)}
function csv(v){return String(v||'').split(',').map(x=>x.trim()).filter(x=>x!=='')}
function nums(v){return csv(v).map(x=>Number(String(x).replace(',','.'))).map(x=>Number.isFinite(x)?x:0)}
function chartSvgMarkup(b,width=640,height=270){
  const labels=csv(b.labels),values=nums(b.values),n=Math.max(1,Math.min(labels.length||values.length,12)),ls=labels.slice(0,n),vs=values.slice(0,n);while(ls.length<n)ls.push(`Dato ${ls.length+1}`);while(vs.length<n)vs.push(0);
  const p=state.word.theme.primary,a=state.word.theme.accent,s=state.word.theme.secondary,target=Number(String(b.target||'').replace(',','.')),hasTarget=Number.isFinite(target)&&String(b.target||'').trim()!=='';
  const unit=esc(b.unit||''),max=Math.max(...vs.map(Math.abs),hasTarget?Math.abs(target):0,1)*1.12;
  const targetLine=(x1,y1,x2,y2)=>hasTarget?`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${a}" stroke-width="2" stroke-dasharray="7 5"/><text x="${x2-2}" y="${Math.max(12,y2-5)}" text-anchor="end" font-size="9" font-weight="800" fill="${p}">Meta ${target}${unit}</text>`:'';
  if(b.chartType==='line'){
    const pts=vs.map((v,i)=>`${58+i*(530/Math.max(1,n-1))},${218-(v/max)*165}`),poly=pts.join(' '),ty=218-(target/max)*165;
    return `<svg class="chart-svg" viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(b.title)}"><line x1="50" y1="218" x2="600" y2="218" stroke="#cbd2dc"/>${targetLine(50,ty,600,ty)}<polyline class="chart-line" points="${poly}" fill="none" stroke="${p}" stroke-width="4" stroke-linejoin="round" stroke-linecap="round"/>${pts.map((pt,i)=>{const [x,y]=pt.split(',');return `<circle class="chart-dot" style="animation-delay:${i*.08}s" cx="${x}" cy="${y}" r="5" fill="${a}" stroke="${p}" stroke-width="2"/><text x="${x}" y="242" text-anchor="middle" font-size="10" fill="#667085">${esc(ls[i])}</text><text x="${x}" y="${+y-10}" text-anchor="middle" font-size="10" font-weight="700" fill="${p}">${vs[i]}${unit}</text>`}).join('')}</svg>`;
  }
  if(b.chartType==='donut'){
    const total=vs.reduce((x,y)=>x+Math.max(0,y),0)||1,cx=205,cy=135,r=78,circ=2*Math.PI*r;let offset=0;const colors=[p,s,a,'#7C3AED','#0E7490','#9A3412'];
    const seg=vs.map((v,i)=>{const len=Math.max(0,v)/total*circ,el=`<circle class="donut-segment" cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="${colors[i%colors.length]}" stroke-width="34" stroke-dasharray="${len} ${circ-len}" stroke-dashoffset="${-offset}" transform="rotate(-90 ${cx} ${cy})"/>`;offset+=len;return el}).join('');
    return `<svg class="chart-svg" viewBox="0 0 ${width} ${height}">${seg}<circle cx="${cx}" cy="${cy}" r="53" fill="#fff"/><text x="${cx}" y="132" text-anchor="middle" font-size="18" font-weight="900" fill="${p}">${vs.reduce((aa,bb)=>aa+bb,0)}${unit}</text><text x="${cx}" y="151" text-anchor="middle" font-size="9" fill="#667085">TOTAL</text>${ls.map((l,i)=>`<rect x="355" y="${55+i*26}" width="12" height="12" rx="3" fill="${colors[i%colors.length]}"/><text x="376" y="${65+i*26}" font-size="10" fill="#344054">${esc(l)} · ${vs[i]}${unit}</text>`).join('')}</svg>`;
  }
  if(b.chartType==='barh'){
    const rowH=Math.min(34,170/n),baseX=145,maxW=430;return `<svg class="chart-svg" viewBox="0 0 ${width} ${height}">${vs.map((v,i)=>{const y=38+i*rowH,w=Math.max(2,(Math.abs(v)/max)*maxW),tx=baseX+w+7;return `<text x="135" y="${y+12}" text-anchor="end" font-size="10" fill="#667085">${esc(ls[i])}</text><rect class="chart-bar-h" style="animation-delay:${i*.07}s" x="${baseX}" y="${y}" width="${w}" height="18" rx="5" fill="${i%2?p:s}"/><text x="${tx}" y="${y+12}" font-size="10" font-weight="700" fill="${p}">${v}${unit}</text>`}).join('')}${hasTarget?`<text x="145" y="245" font-size="9" font-weight="800" fill="${p}">Meta de referencia: ${target}${unit}</text>`:''}</svg>`;
  }
  const gap=10,plotW=530,bw=Math.max(18,(plotW-gap*(n-1))/n),ty=218-(target/max)*165;return `<svg class="chart-svg" viewBox="0 0 ${width} ${height}"><line x1="50" y1="218" x2="600" y2="218" stroke="#cbd2dc"/>${targetLine(50,ty,600,ty)}${vs.map((v,i)=>{const h=Math.max(2,(v/max)*165),x=58+i*(bw+gap),y=218-h;return `<rect class="chart-bar" style="animation-delay:${i*.07}s" x="${x}" y="${y}" width="${bw}" height="${h}" rx="5" fill="${i%2?p:s}"/><text x="${x+bw/2}" y="${y-7}" text-anchor="middle" font-size="10" font-weight="700" fill="${p}">${v}${unit}</text><text x="${x+bw/2}" y="242" text-anchor="middle" font-size="9" fill="#667085">${esc(ls[i])}</text>`}).join('')}</svg>`;
}
function diagramSvgMarkup(b,width=640,height=180){const items=lines(b.items),n=Math.max(1,items.length),nodeW=Math.min(130,(width-50-(n-1)*32)/n),y=58;return `<svg viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">${items.map((x,i)=>{const px=25+i*(nodeW+32);return `${i?`<line x1="${px-29}" y1="${y+31}" x2="${px-5}" y2="${y+31}" stroke="${state.word.theme.accent}" stroke-width="4"/><polygon points="${px-5},${y+31} ${px-13},${y+25} ${px-13},${y+37}" fill="${state.word.theme.accent}"/>`:''}<rect x="${px}" y="${y}" width="${nodeW}" height="62" rx="10" fill="#f5f7fb" stroke="${state.word.theme.primary}"/><text x="${px+nodeW/2}" y="${y+35}" text-anchor="middle" font-size="11" font-weight="700" fill="${state.word.theme.primary}">${esc(x.slice(0,24))}</text>`}).join('')}</svg>`}

function instructivoPreviewHtml(){const d=state.instructivo;return `<article class="paper" data-margin="2.5"><div class="paper-inner">${headerHtml(d.title,d.code,d.version)}<div class="instr-title-band">${esc(d.title)}</div><div class="instr-meta-table"><b>OBJETIVO</b><span>${esc(d.objective)}</span><b>ALCANCE</b><span>${esc(d.scope)}</span></div>${d.steps.length?d.steps.map((s,i)=>`<section class="instruction-step"><div class="instruction-head"><div class="instruction-no">${i+1}</div><div class="instruction-title">${esc(s.title)}</div></div><div class="instruction-body">${esc(s.text).replace(/\n/g,'<br>')}${s.image?`<div class="instruction-image"><img src="${safeImageSrc(s.image)}" alt="Evidencia paso ${i+1}"></div>`:''}${s.note?`<div class="instruction-note"><b>Nota:</b> ${esc(s.note)}</div>`:''}</div></section>`).join(''):'<div class="callout">Agregue el primer paso desde el panel lateral.</div>'}${footerHtml()}</div></article>`}

function shortRef(r){const a=String(r.authors||'Autor').split(';')[0].split(',')[0].trim()||'Autor';return `${a} (${r.year||'s. f.'}) · ${r.title||'Sin título'}`}
function citationAuthors(r){const arr=String(r?.authors||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>x.split(',')[0].trim());if(!arr.length)return 'Autor';if(arr.length===1)return arr[0];if(arr.length===2)return `${arr[0]} & ${arr[1]}`;return `${arr[0]} et al.`}
function formatCitationById(id,locator='',narrative=false){const r=state.word.references.find(x=>x.id===id);if(!r)return 'Fuente no seleccionada';const a=citationAuthors(r),y=r.year||'s. f.',loc=locator?`, ${locator}`:'';if(state.word.citationStyle==='ieee'){const n=Math.max(1,state.word.references.findIndex(x=>x.id===id)+1);return locator?`[${n}, ${locator}]`:`[${n}]`}if(state.word.citationStyle==='iso690')return narrative?`${a.toUpperCase()} (${y}${loc})`:`(${a.toUpperCase()}, ${y}${loc})`;return narrative?`${a} (${y}${loc})`:`(${a}, ${y}${loc})`}
function formatReference(r){const authors=safeText(r.authors||'Autor no identificado',500),year=r.year||'s. f.',title=r.title||'Sin título',source=safeText(r.source||'',1000),url=safeText(r.url||'',1200),style=state.word.citationStyle||'apa7';if(style==='ieee'){const n=Math.max(1,state.word.references.indexOf(r)+1);return `[${n}] ${authors}, “${title},”${source?` ${source},`:''} ${year}.${url?` ${url}`:''}`.trim()}if(style==='iso690')return `${authors.toUpperCase()}. ${title}.${source?` ${source}.`:''} ${year}.${url?` Disponible en: ${url}`:''}`.replace(/\s+/g,' ').trim();return `${authors}. (${year}). ${title}.${source?` ${source}.`:''}${url?` ${url}`:''}`.replace(/\.\./g,'.').replace(/\s+/g,' ').trim()}

function safeImageSrc(src){return /^data:image\/(png|jpeg|jpg|webp|gif);base64,/i.test(String(src||''))?src:''}
function stripDangerousKeys(value,depth=0){if(depth>30)return null;if(Array.isArray(value))return value.slice(0,2000).map(v=>stripDangerousKeys(v,depth+1));if(value&&typeof value==='object'){const out={};for(const [k,v] of Object.entries(value)){if(['__proto__','prototype','constructor'].includes(k))continue;out[k]=stripDangerousKeys(v,depth+1)}return out}if(typeof value==='string')return value.slice(0,1000000);return value}
function normalizeImported(raw){const clean=stripDangerousKeys(raw);if(!clean||typeof clean!=='object')throw new Error('Estructura inválida');const d=defaultState();const merged={...d,...clean,word:{...d.word,...(clean.word||{})},instructivo:{...d.instructivo,...(clean.instructivo||{})}};merged.word.theme={...THEMES.institutional,...(merged.word.theme||{})};merged.word.citationStyle=['apa7','iso690','ieee'].includes(merged.word.citationStyle)?merged.word.citationStyle:'apa7';merged.instructivo.theme={...THEMES.institutional,...(merged.instructivo.theme||{})};merged.word.sections=Array.isArray(merged.word.sections)?merged.word.sections.slice(0,100).map((s,i)=>({id:s.id||uid(),number:String(s.number??s.n??i+1),title:s.title??s.t??`SECCIÓN ${i+1}`,blocks:Array.isArray(s.blocks)?s.blocks.slice(0,400).map(b=>{const x={...b,id:b.id||uid()};if(x.type==='text'){x.style=normalizeTextStyle(x.style);if(x.numbered===undefined)x.numbered=true}if(x.type==='table'){x.tableStyle=x.tableStyle||'institutional';x.align=x.align||'left'}if(x.type==='chart'){x.subtitle=x.subtitle||'';x.unit=x.unit||'';x.target=x.target||''}if(x.type==='citation')x.quote=x.quote||'';return x}):[{...defaultBlock('text'),text:String(s.c??'')}] })):defaultSections(merged.word.type);merged.word.references=Array.isArray(merged.word.references)?merged.word.references.slice(0,200).map(r=>({id:r.id||uid(),type:r.type||'web',authors:r.authors||r.author||'',year:r.year||'',title:r.title||'',source:r.source||r.publisher||'',url:r.url||r.doi||''})):[];merged.instructivo.steps=Array.isArray(merged.instructivo.steps)?merged.instructivo.steps.slice(0,200).map((s,i)=>({id:s.id||uid(),title:s.title||`Paso ${i+1}`,text:s.text||s.description||'',note:s.note||(Array.isArray(s.notes)?s.notes.map(n=>typeof n==='string'?n:n?.text).filter(Boolean).join(' · '):''),image:s.image||s.stepImage||''})):[];merged.route='home';merged.zoom=.78;return merged}
function saveLocal(show=true){localStorage.setItem(STORAGE_KEY,JSON.stringify({...state,dirty:false}));setDirty(false);if(show){saveSnapshot();toast('Proyecto guardado en el navegador.')}}
function loadLocal(){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)state=normalizeImported(JSON.parse(raw))}catch(e){console.warn('No se pudo restaurar el autosave',e)}}
function saveSnapshot(){const hist=getHistory();hist.unshift({label:`${state.word.code||state.instructivo.code||'Proyecto'} · ${state.route==='instructivo'?state.instructivo.title:state.word.title}`,date:new Date().toLocaleString('es-CO'),data:clone(state)});localStorage.setItem(HISTORY_KEY,JSON.stringify(hist.slice(0,8)))}
function getHistory(){try{const h=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');return Array.isArray(h)?h:[]}catch{return []}}
function openHistory(i){const h=getHistory()[i];if(!h)return;state=normalizeImported(h.data);setDirty(true);routeTo('home');toast('Versión local restaurada.','ok')}
function downloadJson(){const payload=JSON.stringify({...state,schemaVersion:2,exportedAt:new Date().toISOString()},null,2);downloadBlob(new Blob([payload],{type:'application/json'}),`${fileBase()}.json`)}
function fileBase(){const s=state.route==='instructivo'?state.instructivo.code:state.word.code;return String(s||'documento-ei').replace(/[^a-z0-9_-]+/gi,'_')}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
async function openJson(file){if(!file)return;if(file.size>MAX_JSON_BYTES){toast('El JSON supera el límite de 5 MB.','error');return}try{const text=await file.text();state=normalizeImported(JSON.parse(text));setDirty(true);routeTo('home');toast('Proyecto importado correctamente.')}catch(e){console.error(e);toast('No se pudo abrir el proyecto JSON.','error')}}

function imageToTarget(file){if(!file)return;if(file.size>MAX_IMAGE_BYTES){toast('La imagen supera el límite de 6 MB.','error');return}if(!/^image\/(png|jpeg|webp|gif)$/i.test(file.type)){toast('Formato de imagen no permitido.','error');return}const r=new FileReader();r.onload=()=>{const src=safeImageSrc(r.result);if(!src){toast('Imagen inválida.','error');return}if(pendingImageTarget?.kind==='block'){const [i,j]=pendingImageTarget.path.split(':').map(Number);state.word.sections[i].blocks[j].src=src}else if(pendingImageTarget?.kind==='step'){state.instructivo.steps[pendingImageTarget.index].image=src}pendingImageTarget=null;changed(true)};r.readAsDataURL(file)}
