
const FLOW_W=850,FLOW_H=580,SNAP=10,EI_BLUE='#00378A';
const $=id=>document.getElementById(id), SVG_NS='http://www.w3.org/2000/svg';
let state=newDemo(), history=[], future=[], clipboard=null, tool='select', connectFrom=null;

function uid(){return'id'+Math.random().toString(36).slice(2,9)}
function clone(o){return JSON.parse(JSON.stringify(o))}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function normColor(c){c=String(c||'#222222').trim();if(/^#[0-9a-fA-F]{6}$/.test(c))return c;if(/^#[0-9a-fA-F]{3}$/.test(c))return '#'+c[1]+c[1]+c[2]+c[2]+c[3]+c[3];return '#222222'}
function cleanPoints(points){return(points||[]).filter(p=>p&&Number.isFinite(+p.x)&&Number.isFinite(+p.y)).map(p=>({x:+p.x,y:+p.y}))}
function snap(v){return state.snap?Math.round(v/SNAP)*SNAP:v}
function activePage(){return state.pages[state.activePage]}
function isFlow(p=activePage()){return p&&p.type==='flow'}
function pushHistory(){history.push(clone({...state,selected:[],selectedEdge:null}));if(history.length>150)history.shift();future=[]}
function restore(s){state=s;state.selected=[];state.selectedEdge=null;renderAll()}

function node(type,text,x,y,lane=0){let n={id:uid(),type,text,x,y,w:112,h:58,lane};setSize(n);return n}
function setSize(n){const m={start:[66,28],end:[66,28],activity:[112,58],decision:[88,88],document:[118,66],delay:[92,58],offpage:[36,44],samepage:[32,32],text:[120,36],note:[120,72],subprocess:[126,62],database:[108,68],manual:[118,56],input:[118,58]};[n.w,n.h]=m[n.type]||[112,58]}

function edgeBetween(p,from,to,label=''){
  const a=p.nodes.find(n=>n.id===from), b=p.nodes.find(n=>n.id===to);
  const [sa,ea]=bestAnchors(a,b), midX=(sa.pt.x+ea.pt.x)/2;
  return {id:uid(),kind:'edge',label,mode:'orthogonal',color:'#222222',width:1.6,style:'solid',arrow:'end',
    start:{attached:true,nodeId:from,side:sa.side,point:sa.pt},
    end:{attached:true,nodeId:to,side:ea.side,point:ea.pt},
    vertices:[{x:midX,y:sa.pt.y},{x:midX,y:ea.pt.y}]
  }
}
function freeEdge(x1,y1,x2,y2){return {id:uid(),kind:'edge',label:'',mode:'orthogonal',color:'#222222',width:1.6,style:'solid',arrow:'end',
  start:{attached:false,point:{x:x1,y:y1}},end:{attached:false,point:{x:x2,y:y2}},vertices:[]}}

function newDemo(){
  const n1=node('start','INICIO',66,86,0), n2=node('activity','RECEPCIONAR solicitud',170,62,0), n3=node('activity','ENVIAR solicitud',338,62,0), n4=node('decision','¿HAY CABLE disponible?',500,44,0), n5=node('activity','INFORMAR novedad',656,62,0), n6=node('activity','VERIFICAR disponibilidad en sistema',210,250,1), n7=node('activity','REALIZAR compromiso en ERP',400,250,1), n8=node('activity','REALIZAR corte',590,426,2), n9=node('offpage','A',760,433,2);
  const p={id:uid(),type:'flow',lanes:[{process:'VENTAS',role:'Asesor comercial'},{process:'LOGÍSTICA',role:'Coordinador logístico'},{process:'LOGÍSTICA',role:'Auxiliares de corte'}],nodes:[n1,n2,n3,n4,n5,n6,n7,n8,n9],edges:[]};
  p.edges=[edgeBetween(p,n1.id,n2.id),edgeBetween(p,n2.id,n3.id),edgeBetween(p,n3.id,n4.id),edgeBetween(p,n4.id,n5.id,'NO'),edgeBetween(p,n4.id,n6.id,'SI'),edgeBetween(p,n6.id,n7.id),edgeBetween(p,n7.id,n8.id),edgeBetween(p,n8.id,n9.id)];
  return {zoom:.78,grid:true,snap:true,activePage:0,selected:[],selectedEdge:null,doc:{title:'PROCEDIMIENTO PARA LA GESTIÓN Y EJECUCIÓN DE CORTE DE CABLES',code:'S-PR-9',version:'Versión 1',date:'17/06/2026'},pages:[p,{id:uid(),type:'narrative',html:`<div class="narrative-grid"><div><p><strong>Reconocimientos:</strong></p><p><strong>Objetivo:</strong> Establecer las actividades para gestionar y ejecutar el corte de cables.</p><p><strong>Alcance:</strong> Aplica desde la recepción de la solicitud hasta la entrega del cable cortado.</p></div><div><p><strong>Normatividad:</strong> Ver normograma.</p><p><strong>Documentos relacionados:</strong></p><ul><li>S-FT-X Registro de corte de cables</li><li>S-IN-X Instructivo aplicable</li></ul></div></div>`}]}
}

function bind(){
  ['docTitle','docCode','docVersion','docDate'].forEach(id=>$(id).addEventListener('change',e=>{pushHistory();const k={docTitle:'title',docCode:'code',docVersion:'version',docDate:'date'}[id];state.doc[k]=e.target.value;renderAll()}));
  document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
  document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addShape(b.dataset.add));
  $('toggleGrid').onclick=()=>{state.grid=!state.grid;renderPages()};$('snapToggle').onclick=()=>{state.snap=!state.snap;renderAll()};
  $('undoBtn').onclick=undo;$('redoBtn').onclick=redo;$('duplicateBtn').onclick=duplicateSelection;$('copyBtn').onclick=copySelection;$('pasteBtn').onclick=pasteSelection;$('deleteBtn').onclick=deleteSelection;
  ['Left','Center','Right','Top','Middle','Bottom'].forEach(k=>$('align'+k).onclick=()=>align(k.toLowerCase()));
  $('distributeH').onclick=()=>distribute('h');$('distributeV').onclick=()=>distribute('v');$('bringFront').onclick=bringFront;$('sendBack').onclick=sendBack;$('autoLayout').onclick=autoLayout;
  $('zoomOut').onclick=()=>setZoom(Math.max(.35,state.zoom-.05));$('zoomIn').onclick=()=>setZoom(Math.min(1.6,state.zoom+.05));$('fitZoom').onclick=()=>setZoom(.78);
  $('loadDemo').onclick=()=>{state=newDemo();history=[];future=[];renderAll()};$('runQA').onclick=showQA;$('saveJson').onclick=saveJson;$('openJson').onchange=openJson;
  $('addFlowPage').onclick=addFlowPage;$('addNarrPage').onclick=addNarrPage;$('dupPage').onclick=dupPage;$('delPage').onclick=delPage;$('addLane').onclick=addLane;
  $('exportSvg').onclick=exportSvg;$('exportHtml').onclick=exportHtml;$('exportPng').onclick=exportPng;$('printPdf').onclick=()=>window.print();
  document.addEventListener('keydown',e=>{if(e.key==='Delete')deleteSelection();if(e.key==='Escape'){state.selected=[];state.selectedEdge=null;setTool('select')}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='c'){e.preventDefault();copySelection()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='v'){e.preventDefault();pasteSelection()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicateSelection()}});
}
function setTool(t){tool=t;connectFrom=null;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));renderPages()}
function renderAll(){
  $('docTitle').value=state.doc.title;$('docCode').value=state.doc.code;$('docVersion').value=state.doc.version;$('docDate').value=state.doc.date;
  $('snapToggle').classList.toggle('active',state.snap);setZoom(state.zoom);renderPageList();renderLaneEditor();renderInspector();renderPages()
}
function setZoom(z){state.zoom=z;$('pagesMount').style.transform=`scale(${z})`;$('zoomLabel').textContent=Math.round(z*100)+'%'}
function renderPageList(){const box=$('pageList');box.innerHTML='';state.pages.forEach((p,i)=>{const d=document.createElement('div');d.className='page-item'+(i===state.activePage?' active':'');d.innerHTML=`<span>${i+1}. ${p.type==='flow'?'Flujograma':'Narrativa'}</span><small>Pág. ${i+1}</small>`;d.onclick=()=>{state.activePage=i;state.selected=[];state.selectedEdge=null;renderAll()};box.appendChild(d)})}
function basePage(idx){const page=document.createElement('article');page.className='proc-page';page.dataset.pageIndex=idx;page.innerHTML=`<div class="proc-inner"><header class="proc-header"><div class="logo-cell"><img src="${LOGO_DATA}"></div><div class="title-cell">${esc(state.doc.title)}</div><div class="meta-cell"><div>${esc(state.doc.code)}</div><div>${esc(state.doc.version)}</div></div></header></div><footer class="proc-footer"><div>${esc(state.doc.date)}</div><div>Pág. ${idx+1} de ${state.pages.length}</div></footer>`;return page}
function renderPages(){const m=$('pagesMount');m.innerHTML='';state.pages.forEach((p,i)=>m.appendChild(p.type==='flow'?flowPage(p,i):narrPage(p,i)))}
function flowPage(p,idx){const page=basePage(idx),inner=page.querySelector('.proc-inner');const sec=document.createElement('section');sec.className='flow-template';sec.innerHTML=`<div class="flow-head"><div class="resp-title">RESPONSABLE</div><div>FLUJOGRAMA</div></div><div class="flow-body"><div class="proc-col"></div><div class="role-col"></div><div class="flow-area ${state.grid?'grid-on':''}"><svg class="flow-svg" viewBox="0 0 ${FLOW_W} ${FLOW_H}" preserveAspectRatio="none"></svg></div></div>`;inner.appendChild(sec);renderLanes(sec,p);renderSvg(sec.querySelector('svg'),p);return page}
function narrPage(p,idx){const page=basePage(idx),inner=page.querySelector('.proc-inner');const sec=document.createElement('section');sec.className='narrative-template';sec.innerHTML=`<div class="narrative-titlebar">Normas y Políticas de la Identificación del Procedimiento</div><div class="narrative-content" contenteditable="true">${p.html||''}</div>`;sec.querySelector('.narrative-content').oninput=e=>{p.html=e.currentTarget.innerHTML};inner.appendChild(sec);return page}
function renderLanes(sec,p){const n=Math.max(1,p.lanes.length),pc=sec.querySelector('.proc-col'),rc=sec.querySelector('.role-col'),area=sec.querySelector('.flow-area');pc.innerHTML='';rc.innerHTML='';p.lanes.forEach((l,i)=>{const top=i/n*100,h=1/n*100;[[pc,l.process],[rc,l.role]].forEach(([col,text])=>{const cell=document.createElement('div');cell.className='lane-cell';cell.style.top=top+'%';cell.style.height=h+'%';cell.innerHTML=`<div class="lane-text">${esc(text)}</div>`;col.appendChild(cell)});if(i<n-1){const line=document.createElement('div');line.className='lane-line';line.style.top=((i+1)/n*100)+'%';area.appendChild(line)}})}

function renderSvg(svg,p){svg.innerHTML=defs();p.edges.forEach(e=>drawEdge(svg,p,e));p.nodes.forEach(n=>svg.appendChild(drawNode(svg,p,n)));svg.onpointerdown=ev=>svgDown(ev,svg,p)}
function defs(){return `<defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L8,4 L0,8 z" fill="#222"/></marker><linearGradient id="grad" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#fff"/><stop offset="1" stop-color="#f1f1f1"/></linearGradient></defs>`}
function svgDown(ev,svg,p){if(tool==='select'){startMarquee(ev,svg,p);return}if(tool==='freeArrow'){const pt=svgPt(svg,ev);pushHistory();const e=freeEdge(snap(pt.x),snap(pt.y),snap(pt.x+120),snap(pt.y));p.edges.push(e);state.selectedEdge=e.id;state.selected=[];setTool('select');renderAll()}}
function startMarquee(ev,svg,p){if(ev.target!==svg)return;state.selected=[];state.selectedEdge=null;const s=svgPt(svg,ev);let rect=null;const move=mv=>{const q=svgPt(svg,mv);if(!rect){rect=el('rect',{class:'marquee'});svg.appendChild(rect)}const x=Math.min(s.x,q.x),y=Math.min(s.y,q.y),w=Math.abs(q.x-s.x),h=Math.abs(q.y-s.y);Object.entries({x,y,width:w,height:h}).forEach(([k,v])=>rect.setAttribute(k,v))};const up=mv=>{const q=svgPt(svg,mv),x=Math.min(s.x,q.x),y=Math.min(s.y,q.y),w=Math.abs(q.x-s.x),h=Math.abs(q.y-s.y);if(w>6&&h>6)state.selected=p.nodes.filter(n=>n.x>=x&&n.y>=y&&n.x+n.w<=x+w&&n.y+n.h<=y+h).map(n=>n.id);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);renderAll()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}

function resolvedPoints(p,e){const start=e.start.attached?anchorByRef(p,e.start):e.start.point;const end=e.end.attached?anchorByRef(p,e.end):e.end.point;let controls=cleanPoints(e.vertices);let raw=[start,...controls,end].filter(Boolean);return e.mode==='straight'?raw:orthogonalize(raw)}
function rawPoints(p,e){const start=e.start.attached?anchorByRef(p,e.start):e.start.point;const end=e.end.attached?anchorByRef(p,e.end):e.end.point;return [start,...cleanPoints(e.vertices),end].filter(Boolean)}
function orthogonalize(raw){if(raw.length<2)return raw;let out=[raw[0]];for(let i=1;i<raw.length;i++){const prev=out[out.length-1],cur=raw[i];if(Math.abs(prev.x-cur.x)<2||Math.abs(prev.y-cur.y)<2)out.push(cur);else out.push({x:cur.x,y:prev.y},cur)}return out}
function drawEdge(svg,p,e){const pts=resolvedPoints(p,e);if(pts.length<2)return;const d='M '+pts.map(pt=>`${pt.x} ${pt.y}`).join(' L ');const path=el('path',{d,class:'edge-path '+(state.selectedEdge===e.id?'edge-selected':''),stroke:normColor(e.color),'stroke-width':e.width||1.6,'stroke-dasharray':e.style==='dashed'?'7 5':(e.style==='dotted'?'2 4':''),'marker-end':e.arrow==='none'?'':'url(#arrow)'});const hit=el('path',{d,class:'edge-hit'});hit.onpointerdown=ev=>edgeDown(ev,svg,p,e);svg.appendChild(path);svg.appendChild(hit);if(e.label){const m=pts[Math.floor(pts.length/2)]||pts[0];const t=el('text',{x:m.x+6,y:m.y-7,class:'edge-label'});t.textContent=e.label;t.ondblclick=ev=>{ev.stopPropagation();const v=prompt('Etiqueta:',e.label);if(v!==null){pushHistory();e.label=v;renderAll()}};svg.appendChild(t)}if(state.selectedEdge===e.id)edgeControls(svg,p,e,pts)}
function edgeControls(svg,p,e,pts){const raw=rawPoints(p,e);raw.forEach((pt,i)=>{const cls=i===0||i===raw.length-1?'edge-end':'edge-vertex';const c=el('circle',{cx:pt.x,cy:pt.y,r:6,class:cls});c.onpointerdown=ev=>startVertexDrag(ev,svg,p,e,i);svg.appendChild(c)});for(let i=0;i<pts.length-1;i++){const a=pts[i],b=pts[i+1],mx=(a.x+b.x)/2,my=(a.y+b.y)/2;const seg=el('rect',{x:mx-5,y:my-5,width:10,height:10,rx:2,class:'edge-segment'});seg.onpointerdown=ev=>startSegmentDrag(ev,svg,p,e,i,pts);svg.appendChild(seg);const add=el('circle',{cx:mx,cy:my,r:3,class:'edge-mid'});add.onpointerdown=ev=>{ev.stopPropagation();pushHistory();e.vertices.push({x:snap(mx),y:snap(my)});renderAll()};svg.appendChild(add)}}
function edgeDown(ev,svg,p,e){ev.stopPropagation();state.selected=[];state.selectedEdge=e.id;renderInspector();renderPages();const start=svgPt(svg,ev), old={start:clone(pointOfEndpoint(p,e,'start')),end:clone(pointOfEndpoint(p,e,'end')),vertices:cleanPoints(e.vertices)};let moved=false;const move=mv=>{moved=true;const q=svgPt(svg,mv),dx=snap(q.x-start.x),dy=snap(q.y-start.y);detachEndpoint(e,'start',old.start);detachEndpoint(e,'end',old.end);e.start.point={x:clamp(old.start.x+dx,0,FLOW_W),y:clamp(old.start.y+dy,0,FLOW_H)};e.end.point={x:clamp(old.end.x+dx,0,FLOW_W),y:clamp(old.end.y+dy,0,FLOW_H)};e.vertices=old.vertices.map(pt=>({x:clamp(pt.x+dx,0,FLOW_W),y:clamp(pt.y+dy,0,FLOW_H)}));renderPages()};const up=()=>{if(moved)pushHistory();window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);renderInspector()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
function startVertexDrag(ev,svg,p,e,i){ev.stopPropagation();const raw=rawPoints(p,e), start=svgPt(svg,ev);let moved=false;const move=mv=>{moved=true;const q=svgPt(svg,mv),pt={x:clamp(snap(q.x),0,FLOW_W),y:clamp(snap(q.y),0,FLOW_H)};if(i===0){detachEndpoint(e,'start',raw[0]);e.start.point=pt}else if(i===raw.length-1){detachEndpoint(e,'end',raw.at(-1));e.end.point=pt}else e.vertices[i-1]=pt;renderPages()};const up=mv=>{if(moved){const q=svgPt(svg,mv);if(i===0)snapEndpointToNode(p,e,'start',q);else if(i===raw.length-1)snapEndpointToNode(p,e,'end',q);pushHistory()}window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);renderInspector();renderAll()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
function startSegmentDrag(ev,svg,p,e,segIndex,pts){ev.stopPropagation();const mid={x:(pts[segIndex].x+pts[segIndex+1].x)/2,y:(pts[segIndex].y+pts[segIndex+1].y)/2};pushHistory();e.vertices.push(mid);state.selectedEdge=e.id;renderAll()}
function detachEndpoint(e,k,pt){e[k].attached=false;e[k].nodeId=null;e[k].side=null;e[k].point={x:pt.x,y:pt.y}}
function pointOfEndpoint(p,e,k){return e[k].attached?anchorByRef(p,e[k]):e[k].point}
function snapEndpointToNode(p,e,k,q){let best=null,dist=22;p.nodes.forEach(n=>['left','right','top','bottom'].forEach(side=>{const a=anchor(n,side),d=Math.hypot(a.x-q.x,a.y-q.y);if(d<dist){dist=d;best={nodeId:n.id,side,point:a}}}));if(best){e[k].attached=true;e[k].nodeId=best.nodeId;e[k].side=best.side;e[k].point=best.point}}
function anchorByRef(p,ref){const n=p.nodes.find(x=>x.id===ref.nodeId);return n?anchor(n,ref.side):ref.point}
function anchor(n,pos){return{left:{x:n.x,y:n.y+n.h/2},right:{x:n.x+n.w,y:n.y+n.h/2},top:{x:n.x+n.w/2,y:n.y},bottom:{x:n.x+n.w/2,y:n.y+n.h}}[pos]}
function bestAnchors(a,b){const dx=(b.x+b.w/2)-(a.x+a.w/2),dy=(b.y+b.h/2)-(a.y+a.h/2);if(Math.abs(dx)>=Math.abs(dy))return dx>=0?[{side:'right',pt:anchor(a,'right')},{side:'left',pt:anchor(b,'left')}]:[{side:'left',pt:anchor(a,'left')},{side:'right',pt:anchor(b,'right')}];return dy>=0?[{side:'bottom',pt:anchor(a,'bottom')},{side:'top',pt:anchor(b,'top')}]:[{side:'top',pt:anchor(a,'top')},{side:'bottom',pt:anchor(b,'bottom')}]}

function drawNode(svg,p,n){const g=el('g',{class:'shape-group '+(state.selected.includes(n.id)?'node-selected':'')});const x=n.x,y=n.y,w=n.w,h=n.h;g.appendChild(el('rect',{x:x-5,y:y-5,width:w+10,height:h+10,rx:6,class:'select-ring'}));
 if(['start','end'].includes(n.type)){g.appendChild(el('rect',{x,y,width:w,height:h,rx:h/2,ry:h/2,fill:EI_BLUE,stroke:'#001e4d','stroke-width':1.2,class:'shape-outline'}));addText(g,n.text,x+w/2,y+h/2,'terminal-text')}
 else if(n.type==='activity'){g.appendChild(el('rect',{x,y,width:w,height:h,fill:'url(#grad)',stroke:'#111','stroke-width':1.2,class:'shape-outline'}));addActivityText(g,n,x+w/2,y+h/2,w)}
 else if(n.type==='decision'){g.appendChild(el('polygon',{points:`${x+w/2},${y} ${x+w},${y+h/2} ${x+w/2},${y+h} ${x},${y+h/2}`,fill:'url(#grad)',stroke:'#111','stroke-width':1.2,class:'shape-outline'}));addWrapped(g,n.text,x+w/2,y+h/2,w*.72,'small-node-text')}
 else if(n.type==='document'){g.appendChild(el('path',{d:`M${x},${y} H${x+w} V${y+h-12} C${x+w-26},${y+h-4} ${x+26},${y+h-20} ${x},${y+h-10} Z`,fill:'url(#grad)',stroke:'#111','stroke-width':1.2,class:'shape-outline'}));addActivityText(g,n,x+w/2,y+h/2-4,w)}
 else if(n.type==='delay'){g.appendChild(el('path',{d:`M${x},${y} H${x+w-h/2} Q${x+w},${y} ${x+w},${y+h/2} Q${x+w},${y+h} ${x+w-h/2},${y+h} H${x} Z`,fill:'url(#grad)',stroke:'#111','stroke-width':1.2,class:'shape-outline'}));addWrapped(g,n.text,x+w/2,y+h/2,w-8,'small-node-text')}
 else if(n.type==='offpage'){g.appendChild(el('polygon',{points:`${x},${y} ${x+w},${y} ${x+w},${y+h*.62} ${x+w/2},${y+h} ${x},${y+h*.62}`,fill:EI_BLUE,stroke:'#001e4d','stroke-width':1.2,class:'shape-outline'}));addText(g,n.text,x+w/2,y+h*.45,'terminal-text')}
 else if(n.type==='samepage'){g.appendChild(el('circle',{cx:x+w/2,cy:y+h/2,r:Math.min(w,h)/2,fill:EI_BLUE,stroke:'#001e4d','stroke-width':1.2,class:'shape-outline'}));addText(g,n.text,x+w/2,y+h/2,'terminal-text')}
 else if(n.type==='note'){g.appendChild(el('path',{d:`M${x},${y} H${x+w-16} L${x+w},${y+16} V${y+h} H${x} Z M${x+w-16},${y} V${y+16} H${x+w}`,fill:'#fff8cc',stroke:'#a08700','stroke-width':1.2,class:'shape-outline'}));addWrapped(g,n.text,x+w/2,y+h/2,w-10,'small-node-text')}
 else if(n.type==='subprocess'){g.appendChild(el('rect',{x,y,width:w,height:h,fill:'url(#grad)',stroke:'#111','stroke-width':1.2,class:'shape-outline'}));g.appendChild(el('line',{x1:x+10,y1:y,x2:x+10,y2:y+h,stroke:'#111'}));g.appendChild(el('line',{x1:x+w-10,y1:y,x2:x+w-10,y2:y+h,stroke:'#111'}));addWrapped(g,n.text,x+w/2,y+h/2,w-22,'small-node-text')}
 else if(n.type==='database'){g.appendChild(el('path',{d:`M${x},${y+12} C${x},${y-3} ${x+w},${y-3} ${x+w},${y+12} V${y+h-12} C${x+w},${y+h+3} ${x},${y+h+3} ${x},${y+h-12} Z M${x},${y+12} C${x},${y+27} ${x+w},${y+27} ${x+w},${y+12}`,fill:'url(#grad)',stroke:'#111','stroke-width':1.2,class:'shape-outline'}));addWrapped(g,n.text,x+w/2,y+h/2,w-8,'small-node-text')}
 else if(n.type==='manual'){g.appendChild(el('path',{d:`M${x},${y} H${x+w} V${y+h} H${x} Z M${x+12},${y} Q${x+20},${y+12} ${x+28},${y}`,fill:'url(#grad)',stroke:'#111','stroke-width':1.2,class:'shape-outline'}));addWrapped(g,n.text,x+w/2,y+h/2,w-10,'small-node-text')}
 else if(n.type==='input'){g.appendChild(el('polygon',{points:`${x+14},${y} ${x+w},${y} ${x+w-14},${y+h} ${x},${y+h}`,fill:'url(#grad)',stroke:'#111','stroke-width':1.2,class:'shape-outline'}));addWrapped(g,n.text,x+w/2,y+h/2,w-18,'small-node-text')}
 else {addWrapped(g,n.text,x+w/2,y+h/2,w,'small-node-text')}
 ['left','right','top','bottom'].forEach(pos=>{const a=anchor(n,pos);g.appendChild(el('circle',{cx:a.x,cy:a.y,r:4,class:'anchor-dot'}))});g.appendChild(el('rect',{x:x+w-5,y:y+h-5,width:10,height:10,class:'resize-handle'}));g.onpointerdown=ev=>nodeDown(ev,svg,p,n);g.ondblclick=ev=>{ev.stopPropagation();const v=prompt('Texto:',n.text);if(v!==null){pushHistory();n.text=v;renderAll()}};return g}
function nodeDown(ev,svg,p,n){ev.stopPropagation();if(tool==='connect'){if(!connectFrom){connectFrom=n.id;state.selected=[n.id];state.selectedEdge=null;renderAll()}else if(connectFrom!==n.id){pushHistory();p.edges.push(edgeBetween(p,connectFrom,n.id));connectFrom=null;state.selected=[];setTool('select');renderAll()}return}const resizing=ev.target.classList&&ev.target.classList.contains('resize-handle');if(ev.shiftKey){if(!state.selected.includes(n.id))state.selected.push(n.id)}else state.selected=[n.id];state.selectedEdge=null;renderInspector();renderPages();const start=svgPt(svg,ev),selected=p.nodes.filter(x=>state.selected.includes(x.id)),old=selected.map(clone);let moved=false;const move=mv=>{moved=true;const q=svgPt(svg,mv),dx=snap(q.x-start.x),dy=snap(q.y-start.y);selected.forEach((node,i)=>{if(resizing&&node.id===n.id){node.w=clamp(old[i].w+dx,24,280);node.h=clamp(old[i].h+dy,20,190)}else{node.x=clamp(old[i].x+dx,0,FLOW_W-node.w);node.y=clamp(old[i].y+dy,0,FLOW_H-node.h);node.lane=laneFromY(p,node.y+node.h/2)}});renderPages()};const up=()=>{if(moved)pushHistory();window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);renderLaneEditor();renderInspector()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
function svgPt(svg,ev){const pt=svg.createSVGPoint();pt.x=ev.clientX;pt.y=ev.clientY;return pt.matrixTransform(svg.getScreenCTM().inverse())}
function el(tag,attrs){const e=document.createElementNS(SVG_NS,tag);Object.entries(attrs||{}).forEach(([k,v])=>{if(v!==null&&v!==undefined&&v!=='')e.setAttribute(k,v)});return e}
function addText(g,text,x,y,cls){const t=el('text',{x,y,class:'node-text '+cls});t.textContent=text;g.appendChild(t)}
function addWrapped(g,text,cx,cy,maxW,cls){const lines=wrap(text,Math.max(9,Math.floor(maxW/7))).slice(0,5),lh=12,sy=cy-(lines.length-1)*lh/2;lines.forEach((line,i)=>addText(g,line,cx,sy+i*lh,cls))}
function addActivityText(g,n,cx,cy,w){const parts=String(n.text).trim().split(/\s+/),verb=(parts.shift()||'').toUpperCase(),rest=parts.join(' ');const t=el('text',{x:cx,y:cy-(rest?8:0),class:'node-text activity-text'}),sp=el('tspan',{class:'verb'});sp.textContent=verb;t.appendChild(sp);g.appendChild(t);if(rest)wrap(rest,Math.max(10,Math.floor(w/7))).slice(0,3).forEach((line,i)=>{const tt=el('text',{x:cx,y:cy+7+i*12,class:'node-text activity-text'}),s=el('tspan',{class:'rest'});s.textContent=line;tt.appendChild(s);g.appendChild(tt)})}
function wrap(text,max){let words=String(text).split(/\s+/).filter(Boolean),lines=[],cur='';words.forEach(w=>{const test=cur?cur+' '+w:w;if(test.length>max&&cur){lines.push(cur);cur=w}else cur=test});if(cur)lines.push(cur);return lines}
function laneFromY(p,y){return clamp(Math.floor(y/(FLOW_H/p.lanes.length)),0,p.lanes.length-1)}

function addShape(type){if(!isFlow())return alert('Selecciona una página de flujograma.');pushHistory();const p=activePage(),n=node(type,defaultText(type),120+p.nodes.length*12,80,0);p.nodes.push(n);state.selected=[n.id];state.selectedEdge=null;renderAll()}
function defaultText(t){return{start:'INICIO',end:'FIN',activity:'REALIZAR actividad',decision:'¿Condición?',document:'REGISTRAR documento',delay:'ESPERAR condición',offpage:'A',samepage:'1',text:'Texto',note:'Nota importante',subprocess:'Subproceso',database:'Base de datos',manual:'Operación manual',input:'Entrada / salida'}[t]||'Texto'}
function renderLaneEditor(){const p=activePage(),pan=$('lanesPanel');pan.style.display=isFlow(p)?'':'none';if(!isFlow(p))return;const box=$('laneEditor');box.innerHTML='';p.lanes.forEach((l,i)=>{const r=document.createElement('div');r.className='lane-row';r.innerHTML=`<label>Proceso<input value="${esc(l.process)}" data-i="${i}" data-k="process"></label><label>Cargo<input value="${esc(l.role)}" data-i="${i}" data-k="role"></label><button data-del="${i}">×</button>`;box.appendChild(r)});box.querySelectorAll('input').forEach(inp=>inp.onchange=e=>{pushHistory();p.lanes[+e.target.dataset.i][e.target.dataset.k]=e.target.value;renderAll()});box.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(p.lanes.length<=1)return;pushHistory();p.lanes.splice(+b.dataset.del,1);p.nodes.forEach(n=>n.lane=clamp(n.lane,0,p.lanes.length-1));renderAll()})}
function renderInspector(){const p=activePage(),box=$('inspector');if(!isFlow(p)){box.innerHTML='Página narrativa editable directamente.';return}
 if(state.selectedEdge){const e=p.edges.find(x=>x.id===state.selectedEdge);if(!e){box.innerHTML='Flecha no encontrada.';return}box.innerHTML=`<label>Etiqueta<input id="edgeLabel" value="${esc(e.label||'')}"></label><div class="grid2"><label>Estilo<select id="edgeStyle"><option value="solid">Continua</option><option value="dashed">Guiones</option><option value="dotted">Puntos</option></select></label><label>Modo<select id="edgeMode"><option value="orthogonal">Ortogonal</option><option value="straight">Recta</option></select></label></div><div class="grid2"><label>Grosor<input id="edgeWidth" type="number" min="1" max="8" step=".2" value="${e.width||1.6}"></label><label>Color<input id="edgeColor" type="color" value="${normColor(e.color)}"></label></div><div class="grid2"><label>Punta<select id="edgeArrow"><option value="end">Final</option><option value="none">Sin punta</option></select></label><label>Vértices<input value="${rawPoints(p,e).length}" disabled></label></div><div class="actions"><button id="addBend">+ Vértice</button><button id="disconnectEdge">Desconectar</button><button id="clearBends">Limpiar vértices</button><button id="reverseEdge">Invertir</button></div><p class="hint">Motor V22: cada flecha tiene sus propios puntos. Arrastrar una flecha no modifica otras ni reordena todas.</p>`;$('edgeStyle').value=e.style||'solid';$('edgeMode').value=e.mode||'orthogonal';$('edgeArrow').value=e.arrow||'end';
   $('edgeLabel').onchange=ev=>{pushHistory();e.label=ev.target.value;renderAll()};$('edgeStyle').onchange=ev=>{pushHistory();e.style=ev.target.value;renderAll()};$('edgeMode').onchange=ev=>{pushHistory();e.mode=ev.target.value;renderAll()};$('edgeWidth').onchange=ev=>{pushHistory();e.width=+ev.target.value||1.6;renderAll()};$('edgeColor').onchange=ev=>{pushHistory();e.color=normColor(ev.target.value);renderAll()};$('edgeArrow').onchange=ev=>{pushHistory();e.arrow=ev.target.value;renderAll()};
   $('addBend').onclick=()=>{pushHistory();const pts=resolvedPoints(p,e),m=pts[Math.floor(pts.length/2)]||{x:200,y:200};e.vertices.push({x:snap(m.x+20),y:snap(m.y+20)});renderAll()};$('disconnectEdge').onclick=()=>{pushHistory();const raw=rawPoints(p,e);e.start={attached:false,point:clone(raw[0])};e.end={attached:false,point:clone(raw.at(-1))};renderAll()};$('clearBends').onclick=()=>{pushHistory();e.vertices=[];renderAll()};$('reverseEdge').onclick=()=>{pushHistory();const s=clone(e.start);e.start=clone(e.end);e.end=s;e.vertices.reverse();renderAll()};return}
 if(state.selected.length){const n=p.nodes.find(x=>x.id===state.selected[0]);box.innerHTML=`<label>Tipo<select id="nodeType">${['start','activity','decision','document','delay','offpage','samepage','end','text','note','subprocess','database','manual','input'].map(t=>`<option value="${t}" ${n.type===t?'selected':''}>${t}</option>`).join('')}</select></label><label>Texto<textarea id="nodeText" rows="3">${esc(n.text)}</textarea></label><label>Carril<select id="nodeLane">${p.lanes.map((l,i)=>`<option value="${i}" ${n.lane===i?'selected':''}>${l.process} | ${l.role}</option>`).join('')}</select></label><div class="grid2"><label>Ancho<input id="nodeW" type="number" value="${Math.round(n.w)}"></label><label>Alto<input id="nodeH" type="number" value="${Math.round(n.h)}"></label></div><div class="grid2"><label>X<input id="nodeX" type="number" value="${Math.round(n.x)}"></label><label>Y<input id="nodeY" type="number" value="${Math.round(n.y)}"></label></div>`;$('nodeType').onchange=ev=>{pushHistory();n.type=ev.target.value;setSize(n);renderAll()};$('nodeText').onchange=ev=>{pushHistory();n.text=ev.target.value;renderAll()};$('nodeLane').onchange=ev=>{pushHistory();n.lane=+ev.target.value;n.y=(n.lane+.5)*(FLOW_H/p.lanes.length)-n.h/2;renderAll()};[['nodeW','w'],['nodeH','h'],['nodeX','x'],['nodeY','y']].forEach(([id,k])=>$(id).onchange=ev=>{pushHistory();n[k]=+ev.target.value||n[k];renderAll()});return}
 box.innerHTML='Selecciona una figura o flecha.'
}

function addLane(){if(!isFlow())return;pushHistory();activePage().lanes.push({process:'PROCESO',role:'Responsable / Cargo'});renderAll()}
function addFlowPage(){pushHistory();state.pages.push({id:uid(),type:'flow',lanes:[{process:'PROCESO',role:'Responsable / Cargo'}],nodes:[],edges:[]});state.activePage=state.pages.length-1;renderAll()}
function addNarrPage(){pushHistory();state.pages.push({id:uid(),type:'narrative',html:'<div class="narrative-grid"><div><p><strong>Objetivo:</strong></p><p><strong>Alcance:</strong></p></div><div><p><strong>Documentos relacionados:</strong></p><ul><li>X-X-X</li></ul></div></div>'});state.activePage=state.pages.length-1;renderAll()}
function dupPage(){pushHistory();const cp=clone(activePage());cp.id=uid();state.pages.splice(state.activePage+1,0,cp);state.activePage++;renderAll()}
function delPage(){if(state.pages.length<=1)return;pushHistory();state.pages.splice(state.activePage,1);state.activePage=Math.max(0,state.activePage-1);renderAll()}
function duplicateSelection(){if(!isFlow()||!state.selected.length)return;pushHistory();const p=activePage(),ids=[];state.selected.forEach(id=>{const n=clone(p.nodes.find(x=>x.id===id));n.id=uid();n.x+=25;n.y+=25;p.nodes.push(n);ids.push(n.id)});state.selected=ids;renderAll()}
function copySelection(){if(!isFlow()||!state.selected.length)return;const p=activePage();clipboard={nodes:p.nodes.filter(n=>state.selected.includes(n.id)).map(clone),edges:[]}}
function pasteSelection(){if(!isFlow()||!clipboard)return;pushHistory();const p=activePage(),ids=[];clipboard.nodes.forEach(old=>{const n=clone(old);n.id=uid();n.x+=30;n.y+=30;p.nodes.push(n);ids.push(n.id)});state.selected=ids;renderAll()}
function deleteSelection(){const p=activePage();if(!isFlow(p))return;if(state.selectedEdge){pushHistory();p.edges=p.edges.filter(e=>e.id!==state.selectedEdge);state.selectedEdge=null;renderAll();return}if(state.selected.length){pushHistory();const s=new Set(state.selected);p.nodes=p.nodes.filter(n=>!s.has(n.id));p.edges=p.edges.filter(e=>!(e.start.attached&&s.has(e.start.nodeId))&&!(e.end.attached&&s.has(e.end.nodeId)));state.selected=[];renderAll()}}
function align(mode){if(!isFlow()||state.selected.length<2)return;pushHistory();const ns=activePage().nodes.filter(n=>state.selected.includes(n.id));if(mode==='left'){const x=Math.min(...ns.map(n=>n.x));ns.forEach(n=>n.x=x)}if(mode==='center'){const cx=ns.reduce((a,n)=>a+n.x+n.w/2,0)/ns.length;ns.forEach(n=>n.x=cx-n.w/2)}if(mode==='right'){const r=Math.max(...ns.map(n=>n.x+n.w));ns.forEach(n=>n.x=r-n.w)}if(mode==='top'){const y=Math.min(...ns.map(n=>n.y));ns.forEach(n=>n.y=y)}if(mode==='middle'){const cy=ns.reduce((a,n)=>a+n.y+n.h/2,0)/ns.length;ns.forEach(n=>n.y=cy-n.h/2)}if(mode==='bottom'){const b=Math.max(...ns.map(n=>n.y+n.h));ns.forEach(n=>n.y=b-n.h)}renderAll()}
function distribute(axis){if(!isFlow()||state.selected.length<3)return;pushHistory();const ns=activePage().nodes.filter(n=>state.selected.includes(n.id)).sort((a,b)=>axis==='h'?a.x-b.x:a.y-b.y);const first=axis==='h'?ns[0].x:ns[0].y,last=axis==='h'?ns.at(-1).x:ns.at(-1).y,step=(last-first)/(ns.length-1);ns.forEach((n,i)=>{if(axis==='h')n.x=first+i*step;else n.y=first+i*step});renderAll()}
function bringFront(){if(!isFlow()||!state.selected.length)return;pushHistory();const p=activePage(),sel=p.nodes.filter(n=>state.selected.includes(n.id));p.nodes=p.nodes.filter(n=>!state.selected.includes(n.id)).concat(sel);renderAll()}
function sendBack(){if(!isFlow()||!state.selected.length)return;pushHistory();const p=activePage(),sel=p.nodes.filter(n=>state.selected.includes(n.id));p.nodes=sel.concat(p.nodes.filter(n=>!state.selected.includes(n.id)));renderAll()}
function autoLayout(){if(!isFlow())return;pushHistory();const p=activePage(),by={};p.nodes.forEach(n=>(by[n.lane]??=[]).push(n));Object.entries(by).forEach(([lane,arr])=>arr.forEach((n,i)=>{n.x=70+i*145;n.y=(+lane+.5)*(FLOW_H/p.lanes.length)-n.h/2}));renderAll()}
function undo(){if(!history.length)return;future.push(clone(state));restore(history.pop())}
function redo(){if(!future.length)return;history.push(clone(state));restore(future.pop())}
function normalizeState(){(state.pages||[]).forEach(p=>{if(p.type==='flow'){p.nodes=(p.nodes||[]).filter(n=>n&&Number.isFinite(+n.x)&&Number.isFinite(+n.y));p.edges=(p.edges||[]).filter(e=>e&&e.start&&e.end);p.edges.forEach(e=>{e.color=normColor(e.color);e.vertices=cleanPoints(e.vertices);if(!e.mode)e.mode='orthogonal';if(!e.width)e.width=1.6;if(!e.style)e.style='solid';if(!e.arrow)e.arrow='end'})}})}
function saveJson(){download(JSON.stringify(state,null,2),(state.doc.code||'procedimiento')+'.json','application/json')}
function openJson(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);normalizeState();renderAll()}catch(err){alert('JSON inválido')}};r.readAsText(f)}
function exportSvg(){const svg=document.querySelector(`.proc-page[data-page-index="${state.activePage}"] .flow-svg`);if(!svg)return alert('Selecciona una página de flujograma.');download(svg.outerHTML,(state.doc.code||'flujo')+'_flujo.svg','image/svg+xml')}
function exportHtml(){const html='<!doctype html><html><head><meta charset="utf-8"><style>'+document.querySelector('style').innerHTML+'</style></head><body><div class="pages" style="transform:none">'+$('pagesMount').innerHTML+'</div></body></html>';download(html,(state.doc.code||'procedimiento')+'.html','text/html')}
function exportPng(){alert('Para máxima fidelidad usa PDF o SVG. El PNG completo requiere rasterizado de HTML; se deja como salida secundaria para fase posterior.')}
function download(content,name,type){const b=new Blob([content],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function runQA(){const out=[];out.push({ok:state.pages.length>0,msg:'Existe al menos una página'});state.pages.forEach((p,idx)=>{if(p.type==='flow'){out.push({ok:p.lanes.length>0,msg:`Pág. ${idx+1}: tiene carriles`});out.push({ok:p.nodes.every(n=>n.x>=0&&n.y>=0&&n.x+n.w<=FLOW_W&&n.y+n.h<=FLOW_H),msg:`Pág. ${idx+1}: figuras dentro del área`});out.push({ok:p.edges.every(e=>rawPoints(p,e).length>=2),msg:`Pág. ${idx+1}: flechas con puntos válidos`});out.push({ok:p.edges.every(e=>/^#[0-9a-fA-F]{6}$/.test(normColor(e.color))),msg:`Pág. ${idx+1}: colores de flecha válidos`})}});return out}
function showQA(){const box=$('qaBox'),res=runQA();box.hidden=false;box.innerHTML='<h3>Examen QA V22</h3>'+res.map(r=>`<p class="${r.ok?'qa-pass':'qa-fail'}">${r.ok?'✓':'•'} ${esc(r.msg)}</p>`).join('')+'<button id="closeQA">Cerrar</button>';$('closeQA').onclick=()=>box.hidden=true}
function init(){bind();normalizeState();renderAll();console.log('V22 stable arrow core loaded',runQA())}
init();
